#!/usr/bin/env python3
"""Generate quiz-batch-626-650.json from reviewed question data."""
import json
from pathlib import Path

META = {
    "type": "multiple_choice",
    "sourceLinks": [],
    "status": "published",
    "reviewStatus": "approved",
    "sourceChecked": True,
    "wordingChecked": True,
    "metaChecked": True,
    "logicChecked": True,
    "duplicateChecked": True,
    "reviewedBy": "DAR AL TAWḤĪD Content Review",
    "reviewedAt": "2026-07-18T00:00:00.000Z",
    "createdAt": "2026-07-18T00:00:00.000Z",
    "updatedAt": "2026-07-18T00:00:00.000Z",
    "reviewNotes": "Fortgeschrittene eigenständige Wissensfrage; keine Meta-, Block- oder App-Frage. Aussage, Antwortlogik und Fundstelle geprüft.",
    "validationErrors": [],
}


def q(num, category, topic, level, question, answers, correct_index, explanation, source_type, source, sensitivity="normal"):
    return {
        "id": f"quiz-{num}",
        "number": num,
        "category": category,
        "topic": topic,
        "level": level,
        "question": question,
        "answers": answers,
        "correctIndex": correct_index,
        "explanation": explanation,
        "sourceType": source_type,
        "source": source,
        "sensitivity": sensitivity,
        **META,
    }


QUESTIONS = [
    q(626, "Ṣaḥābah und Fiqh", "Zusammenlegen der Gebete ohne Reise", "Fortgeschritten",
      "Welche Begründung überlieferte Ibn ʿAbbās رضي الله عنهما dafür, dass der Prophet ﷺ in Medina Ẓuhr mit ʿAṣr und Maghrib mit ʿIschāʾ zusammenlegte, obwohl weder Furcht noch Regen vorlagen?",
      ["Die regulären Gebetszeiten waren zu diesem Zeitpunkt noch nicht festgelegt.",
       "Das Zusammenlegen sollte von da an zur täglichen Regel werden.",
       "Der Ummah sollte keine unnötige Bedrängnis auferlegt werden.",
       "Die Gebete wurden wegen einer unmittelbar bevorstehenden Reise vorgezogen."],
      2, "Ibn ʿAbbās erklärte, dass der Prophet ﷺ seiner Ummah keine unnötige Bedrängnis bereiten wollte. Die Überlieferung ist eine wichtige Grundlage in der fiqhrechtlichen Diskussion über das Zusammenlegen bei tatsächlichem Bedarf.",
      "Ṣaḥīḥ Ḥadīth / Aussage eines Ṣaḥābī", "Ṣaḥīḥ Muslim 705d"),
    q(627, "Ṣaḥābah und Fiqh", "Ehe ohne festgelegte Brautgabe", "Fortgeschritten",
      "Wie urteilte Ibn Masʿūd رضي الله عنه über eine Frau, deren Ehemann starb, bevor eine Brautgabe festgelegt oder die Ehe vollzogen worden war?",
      ["Sie erhielt weder Brautgabe noch Erbanteil und musste keine Wartezeit einhalten.",
       "Sie erhielt eine angemessene Brautgabe vergleichbarer Frauen, erbte und musste die ʿIddah einhalten.",
       "Sie erhielt ausschließlich den Erbanteil, aber keine Brautgabe.",
       "Die Ehe wurde rückwirkend als nicht geschlossen behandelt."],
      1, "Ibn Masʿūd entschied auf vollständige angemessene Brautgabe, Erbanteil und Einhaltung der Wartezeit. Maʿqil ibn Sinān bestätigte anschließend, dass der Prophet ﷺ im Fall von Birwaʿ bint Wāšiq ebenso geurteilt hatte.",
      "Ṣaḥīḥ Ḥadīth / Fiqh-Urteil eines Ṣaḥābī", "Sunan Abī Dāwūd 2114"),
    q(628, "Ṣaḥābah und Uṣūl", "Offenbarung vor bloßer Vernunftmeinung", "Fortgeschritten",
      "Welche methodische Lehre verdeutlichte ʿAlī ibn Abī Ṭālib رضي الله عنه mit seiner Aussage über das Streichen über die Ledersocken?",
      ["Rechtsurteile dürfen ausschließlich nach körperlicher Bequemlichkeit bestimmt werden.",
       "Der untere Teil der Ledersocke muss stets gestrichen werden.",
       "Bei Ṭahārah darf grundsätzlich kein Qiyās verwendet werden.",
       "Eine scheinbar vernünftige Überlegung wird verlassen, wenn eine bestätigte prophetische Praxis das Gegenteil zeigt."],
      3, "ʿAlī erklärte, dass bei bloßer Vernunftbetrachtung die Unterseite eher gestrichen würde, er den Propheten ﷺ jedoch über die Oberseite der Ledersocken streichen sah. Der bestätigte Text besitzt Vorrang vor einer entgegenstehenden bloßen Einschätzung.",
      "Ṣaḥīḥ Athar / Sunnah", "Sunan Abī Dāwūd 162", "sensitive"),
    q(629, "Ṣaḥābah und Gebetsfiqh", "Gebet auf dem Reittier", "Fortgeschritten",
      "Welche Unterscheidung überlieferte Ibn ʿUmar رضي الله عنهما über das Gebet des Reisenden auf einem Reittier?",
      ["Sowohl Pflicht- als auch freiwillige Gebete wurden ohne Ausnahme auf dem Reittier verrichtet.",
       "Nur das Pflichtgebet durfte unabhängig von der Gebetsrichtung auf dem Reittier verrichtet werden.",
       "Freiwillige Gebete und Witr konnten auf dem Reittier verrichtet werden, nicht jedoch das reguläre Pflichtgebet.",
       "Das Gebet auf einem Reittier war ausschließlich während des Ḥajj erlaubt."],
      2, "Ibn ʿUmar berichtete, dass der Prophet ﷺ freiwillige Gebete und Witr auf seinem Reittier in dessen jeweiliger Bewegungsrichtung verrichtete, das Pflichtgebet jedoch nicht auf diese Weise betete.",
      "Ṣaḥīḥ Ḥadīth / Athar", "Ṣaḥīḥ al-Bukhārī 1098"),
    q(630, "Ṣaḥābah und Gebetsfiqh", "Ursprung des Reisegebets", "Fortgeschritten",
      "Welche Entwicklung der Anzahl der Rakʿāt beschrieb ʿĀʾischah رضي الله عنها?",
      ["Das Reisegebet wurde ursprünglich mit vier Rakʿāt vorgeschrieben und später verkürzt.",
       "Die Gebete wurden ursprünglich mit zwei Rakʿāt vorgeschrieben; das Reisegebet blieb so, während das Gebet des Ansässigen erweitert wurde.",
       "Nur das Fajr-Gebet bestand ursprünglich aus zwei Rakʿāt.",
       "Die Anzahl der Rakʿāt wurde erst nach dem Tod des Propheten ﷺ festgelegt."],
      1, "ʿĀʾischah berichtete, dass die Gebete zunächst mit zwei Rakʿāt vorgeschrieben wurden. Die Reisegebete blieben auf diesem ursprünglichen Umfang, während die Gebete im Aufenthaltsort erweitert wurden.",
      "Ṣaḥīḥ Ḥadīth / Aussage einer Ṣaḥābiyyah", "Ṣaḥīḥ al-Bukhārī 350"),
    q(631, "Ṣaḥābah und Erbrecht", "Tochter, Sohnestochter und Schwester", "Fortgeschritten",
      "Wie verteilte Ibn Masʿūd رضي الله عنه den Nachlass, wenn eine Tochter, eine Sohnestochter und eine Schwester vorhanden waren?",
      ["Die Tochter erhielt die Hälfte und die Schwester die andere Hälfte; die Sohnestochter erhielt nichts.",
       "Die Sohnestochter erhielt die Hälfte und die Tochter ein Sechstel.",
       "Die Tochter und die Sohnestochter erhielten jeweils ein Drittel; die Schwester erhielt den Rest.",
       "Die Tochter erhielt die Hälfte, die Sohnestochter ein Sechstel zur Ergänzung von zwei Dritteln und die Schwester den Rest."],
      3, "Ibn Masʿūd erklärte, dass er nach dem Urteil des Propheten ﷺ entscheide: die Tochter erhält die Hälfte, die Sohnestochter ein Sechstel und die Schwester den verbleibenden Anteil.",
      "Ṣaḥīḥ Ḥadīth / Farāʾiḍ", "Ṣaḥīḥ al-Bukhārī 6736 und 6742"),
    q(632, "Ṣaḥābah und Erbrecht", "Tochter und Schwester als Erbinnen", "Fortgeschritten",
      "Wie entschied Muʿādh ibn Jabal رضي الله عنه über einen Nachlass, bei dem nur eine Tochter und eine Schwester als Erbinnen vorhanden waren?",
      ["Die Tochter erhielt die Hälfte und die Schwester die andere Hälfte.",
       "Die Tochter erhielt den gesamten Nachlass.",
       "Die Schwester erhielt zwei Drittel und die Tochter ein Drittel.",
       "Beide erhielten jeweils ein Drittel; der Rest fiel an die Staatskasse."],
      0, "Muʿādh gab der Tochter die Hälfte und der Schwester die andere Hälfte. Der Bericht zeigt die Stellung der Schwester als ʿaṣabah zusammen mit einer Tochter.",
      "Ṣaḥīḥ Athar / Farāʾiḍ", "Ṣaḥīḥ al-Bukhārī 6734 und 6741"),
    q(633, "Ulema und Rechtsschulen", "Überlieferung der Mudawwanah", "Fortgeschritten",
      "Welche Überlieferungs- und Redaktionsverbindung steht hinter dem mālikitischen Grundlagenwerk al-Mudawwanah?",
      ["Al-Bukhārī sammelte darin ausschließlich Rechtsmeinungen von Mālik.",
       "Asch-Schāfiʿī überlieferte darin die Antworten Abū Ḥanīfahs.",
       "Saḥnūn überlieferte und ordnete Material von Ibn al-Qāsim, das wesentlich auf dessen Kenntnis der Rechtslehre Māliks beruhte.",
       "Ibn Ḥazm fasste darin die Positionen der vier Rechtsschulen zusammen."],
      2, "Al-Mudawwanah ist eng mit Saḥnūn und seinem Lehrer Ibn al-Qāsim verbunden. Ibn al-Qāsim gehörte zu den wichtigsten Überlieferern des Fiqh von Imām Mālik.",
      "Mālikitisches Grundlagenwerk", "Saḥnūn, al-Mudawwanah al-Kubrā, Einleitung und Überlieferungsstruktur"),
    q(634, "Ulema und Ḥanafitischer Fiqh", "Al-Siyar al-Kabīr", "Fortgeschritten",
      "Welchen juristischen Themenbereich behandelt Muḥammad asch-Schaybānīs Werk al-Siyar al-Kabīr schwerpunktmäßig?",
      ["Ausschließlich Regeln der rituellen Reinheit.",
       "Beziehungen zwischen Gemeinwesen, Verträge, Sicherheit, Krieg, Frieden und verwandte Rechtsfragen.",
       "Nur die Biographien der Überlieferer von Kūfah.",
       "Ausschließlich Erbrecht und Testamente."],
      1, "Al-Siyar al-Kabīr gehört zu den bedeutenden frühen Werken über internationale und zwischenstaatliche Rechtsfragen im klassischen islamischen Fiqh.",
      "Ḥanafitisches Grundlagenwerk", "Muḥammad ibn al-Ḥasan asch-Schaybānī, al-Siyar al-Kabīr; as-Saraḫsī, Šarḥ as-Siyar al-Kabīr"),
    q(635, "Ulema und Vergleichender Fiqh", "Methode von Bidāyat al-Muǧtahid", "Fortgeschritten",
      "Welche methodische Besonderheit kennzeichnet Ibn Rušds Bidāyat al-Muǧtahid?",
      ["Das Werk nennt ausschließlich die mālikitische Position ohne andere Auffassungen.",
       "Es sammelt hauptsächlich Überliefererbiographien.",
       "Es behandelt nur Rechtsfragen, über die vollständiger Konsens besteht.",
       "Es vergleicht Rechtspositionen, ihre Belege und die Ursachen der Meinungsverschiedenheit."],
      3, "Ibn Rušd stellt unterschiedliche Rechtspositionen gegenüber und erklärt häufig, welche unterschiedlichen Textverständnisse oder methodischen Grundlagen zur Abweichung führten.",
      "Vergleichender Fiqh", "Ibn Rušd, Bidāyat al-Muǧtahid wa-Nihāyat al-Muqtaṣid"),
    q(636, "Ulema und Ẓāhiritischer Fiqh", "Methode von al-Muḥallā", "Fortgeschritten",
      "Welche Beschreibung trifft auf Ibn Ḥazms Werk al-Muḥallā am ehesten zu?",
      ["Es ist ein umfangreiches Fiqh-Werk mit stark textbezogener ẓāhiritischer Argumentation und ausführlicher Prüfung gegnerischer Positionen.",
       "Es ist ausschließlich eine Sammlung ungeordneter Gedichte.",
       "Es ist ein mālikitischer Kurzkommentar zu al-Muwaṭṭaʾ.",
       "Es behandelt nur die Grammatik des klassischen Arabisch."],
      0, "Al-Muḥallā verbindet Fiqh-Fragen mit Qurʾān-, Ḥadīth- und Athar-Belegen und vertritt dabei die textbezogene Methodik Ibn Ḥazms.",
      "Ẓāhiritisches Fiqh-Werk", "Ibn Ḥazm, al-Muḥallā bi-l-Āṯār"),
    q(637, "Ulema und Schāfiʿitischer Fiqh", "Al-Maǧmūʿ", "Fortgeschritten",
      "Welche Funktion besitzt an-Nawawīs al-Maǧmūʿ Šarḥ al-Muhaḏḏab?",
      ["Es ist lediglich ein Wörterbuch für seltene arabische Begriffe.",
       "Es enthält ausschließlich die Biographie Imām asch-Schāfiʿīs.",
       "Es kommentiert al-Muhaḏḏab, erklärt den schāfiʿitischen Fiqh und vergleicht vielfach Belege und Positionen anderer Gelehrter.",
       "Es ist eine reine Sammlung von Ḥadīthen ohne Fiqh-Kommentierung."],
      2, "Al-Maǧmūʿ ist eines der umfangreichsten Werke des schāfiʿitischen Fiqh und enthält neben der Madhhab-Darstellung zahlreiche vergleichende und hadithkritische Erörterungen.",
      "Schāfiʿitisches Grundlagenwerk", "An-Nawawī, al-Maǧmūʿ Šarḥ al-Muhaḏḏab"),
    q(638, "Ulema und Mālikitischer Fiqh", "Al-Istiḏkār", "Fortgeschritten",
      "Womit beschäftigt sich Ibn ʿAbd al-Barr in al-Istiḏkār?",
      ["Ausschließlich mit der Genealogie arabischer Stämme.",
       "Mit den in al-Muwaṭṭaʾ enthaltenen Āthār und Rechtsfragen sowie den Auffassungen der Fuqahāʾ verschiedener Regionen.",
       "Nur mit den Regeln der Qurʾān-Kalligraphie.",
       "Ausschließlich mit den Rechtsurteilen Abū Ḥanīfahs."],
      1, "Al-Istiḏkār behandelt die Überlieferungen und Rechtsfragen von al-Muwaṭṭaʾ und stellt dabei zahlreiche Positionen früher Rechtsgelehrter vergleichend dar.",
      "Ḥadīth-Kommentar / Vergleichender Fiqh", "Ibn ʿAbd al-Barr, al-Istiḏkār li-Maḏāhib Fuqahāʾ al-Amṣār"),
    q(639, "Uṣūl al-Fiqh", "Taḫṣīṣ al-ʿĀmm", "Fortgeschritten",
      "Was bedeutet Taḫṣīṣ al-ʿĀmm in der Rechtsmethodik?",
      ["Einen besonderen Text auf alle denkbaren Fälle auszudehnen.",
       "Einen Text wegen sprachlicher Schwierigkeit vollständig aufzuheben.",
       "Eine allgemeine Aussage ausschließlich nach persönlicher Vorliebe auszulegen.",
       "Den Anwendungsbereich einer allgemeinen Aussage durch einen anerkannten Beleg einzuschränken."],
      3, "Beim Taḫṣīṣ bleibt der allgemeine Text bestehen, jedoch werden bestimmte Fälle aufgrund eines anerkannten spezifizierenden Belegs aus seinem Umfang herausgenommen.",
      "Uṣūl al-Fiqh", "Al-Ġazālī, al-Mustaṣfā, Bāb al-ʿĀmm wa-l-Ḫāṣṣ; Ibn Qudāmah, Rawḍat an-Nāẓir, Bāb al-ʿĀmm wa-l-Ḫāṣṣ"),
    q(640, "Uṣūl al-Fiqh", "Muṭlaq und Muqayyad", "Fortgeschritten",
      "Worin unterscheidet sich ein muṭlaq formulierter Text von einem muqayyad formulierten Text?",
      ["Der muṭlaq nennt eine Sache ohne einschränkende Eigenschaft, während der muqayyad sie mit einer zusätzlichen Einschränkung verbindet.",
       "Der muṭlaq ist immer aufgehoben und der muqayyad immer schwach.",
       "Der muqayyad besitzt niemals rechtliche Bedeutung.",
       "Beide Begriffe bezeichnen ausschließlich unterschiedliche Lesarten des Qurʾān."],
      0, "Die Frage, ob eine uneingeschränkte Aussage aufgrund eines anderen eingeschränkten Textes eingeschränkt wird, hängt von methodischen Voraussetzungen wie Urteil und Rechtsgrund ab.",
      "Uṣūl al-Fiqh", "Asch-Schāfiʿī, al-Risālah; al-Ġazālī, al-Mustaṣfā, Bāb al-Muṭlaq wa-l-Muqayyad"),
    q(641, "Uṣūl al-Fiqh", "Mafhūm al-Muḫālafah", "Fortgeschritten",
      "Was wird mit Mafhūm al-Muḫālafah bezeichnet?",
      ["Das vollständige Ignorieren der ausdrücklichen Textaussage.",
       "Das Aufheben eines Ḥadīths durch eine persönliche Meinung.",
       "Unter bestimmten Voraussetzungen aus einer genannten Einschränkung ein abweichendes Urteil für den nicht genannten Gegenfall abzuleiten.",
       "Die Behauptung, jeder sprachliche Unterschied sei ein Widerspruch."],
      2, "Beim Mafhūm al-Muḫālafah wird geprüft, ob die ausdrückliche Bindung eines Urteils an eine Eigenschaft darauf hinweist, dass der Gegenfall anders zu beurteilen ist. Nicht jede Beschreibung erfüllt dafür die notwendigen Bedingungen.",
      "Uṣūl al-Fiqh", "Al-Ġazālī, al-Mustaṣfā, Bāb al-Mafhūm; Ibn Qudāmah, Rawḍat an-Nāẓir, Bāb Dalīl al-Ḫiṭāb"),
    q(642, "Uṣūl al-Fiqh", "Dalālat al-Iqtiḍāʾ", "Fortgeschritten",
      "Was kennzeichnet Dalālat al-Iqtiḍāʾ?",
      ["Eine Bedeutung, die nur wegen eines Reims angenommen wird.",
       "Eine nicht ausdrücklich genannte Bedeutung, die vorausgesetzt werden muss, damit die Aussage wahr, verständlich oder rechtlich korrekt ist.",
       "Die vollständige Verwerfung der sprachlichen Textbedeutung.",
       "Eine Rechtsmeinung ohne irgendeinen Bezug zum Text."],
      1, "Bei Dalālat al-Iqtiḍāʾ verlangt die sprachliche oder rechtliche Richtigkeit einer Aussage die gedankliche Ergänzung eines nicht ausdrücklich ausgesprochenen Elements.",
      "Uṣūl al-Fiqh", "As-Saraḫsī, Uṣūl as-Saraḫsī, Bāb Dalālāt an-Naẓm; al-Bazdawī, Kanz al-Wuṣūl"),
    q(643, "Uṣūl al-Fiqh", "Aussage eines Ṣaḥābī", "Fortgeschritten",
      "Warum ist die einzelne Rechtsaussage eines Ṣaḥābī nicht automatisch mit Ijmāʿ gleichzusetzen?",
      ["Weil Aussagen der Ṣaḥābah grundsätzlich keinen Wert besitzen.",
       "Weil ein Ṣaḥābī niemals Iǧtihād ausübte.",
       "Weil nur spätere Gelehrte einen Konsens bilden können.",
       "Weil eine einzelne Aussage noch keine nachgewiesene Übereinstimmung aller qualifizierten Gelehrten darstellt."],
      3, "Die Beweiskraft des qawl aṣ-Ṣaḥābī wird in der Uṣūl-Literatur differenziert behandelt. Eine einzelne Aussage ist jedoch begrifflich kein Ijmāʿ, solange keine allgemeine Übereinstimmung nachgewiesen ist.",
      "Uṣūl al-Fiqh", "Ibn Qudāmah, Rawḍat an-Nāẓir, Bāb Qawl aṣ-Ṣaḥābī; al-Ġazālī, al-Mustaṣfā"),
    q(644, "Vergleichender Fiqh", "Ehevertrag einer volljährigen Frau", "Fortgeschritten",
      "Welche klassische Meinungsverschiedenheit besteht über den Ehevertrag einer volljährigen, verständigen Frau?",
      ["Die ḥanafitische Schule erlaubt ihr grundsätzlich den eigenen Vertragsabschluss unter rechtlichen Bedingungen; die Mehrheit verlangt einen Walī.",
       "Alle vier Rechtsschulen erklären den Walī ausnahmslos für bedeutungslos.",
       "Nur die schāfiʿitische Schule erlaubt den eigenen Vertragsabschluss ohne Walī.",
       "Die mālikitische und ḥanbalitische Schule verbieten jeden Ehevertrag durch einen Walī."],
      0, "Im ḥanafitischen Fiqh kann eine volljährige und verständige Frau grundsätzlich selbst einen Ehevertrag schließen, wobei Fragen wie Ebenbürtigkeit und angemessene Brautgabe rechtlich relevant bleiben. Die Mehrheit der übrigen Schulen betrachtet den Walī als Gültigkeitsvoraussetzung.",
      "Vergleichender Fiqh", "Al-Marġīnānī, al-Hidāyah, Kitāb an-Nikāḥ; an-Nawawī, al-Maǧmūʿ; Ibn Qudāmah, al-Muġnī", "sensitive"),
    q(645, "Vergleichender Fiqh", "Zakāh auf getragenen Goldschmuck", "Fortgeschritten",
      "Welche bekannte Meinungsverschiedenheit besteht über rechtmäßig getragenen Goldschmuck, der den Niṣāb erreicht?",
      ["Alle vier Rechtsschulen erklären ihn ausnahmslos für nicht zakāhpflichtig.",
       "Nur die mālikitische Schule erklärt jeden Schmuck für zakāhpflichtig.",
       "Die ḥanafitische Schule verlangt grundsätzlich Zakāh; die Mehrheit befreit üblichen rechtmäßig genutzten Schmuck unter ihren Bedingungen.",
       "Schmuck ist nur dann zakāhpflichtig, wenn er niemals getragen wurde."],
      2, "Die ḥanafitische Schule behandelt Gold und Silber grundsätzlich auch in Schmuckform als zakāhpflichtig. Die Mehrheit unterscheidet bei zulässigem, üblichem Gebrauch und sieht hierfür grundsätzlich keine Zakāh vor, solange keine weiteren Gründe wie Handel oder übermäßige Hortung vorliegen.",
      "Vergleichender Fiqh", "Al-Kāsānī, Badāʾiʿ aṣ-Ṣanāʾiʿ, Kitāb az-Zakāh; an-Nawawī, al-Maǧmūʿ; Ibn Qudāmah, al-Muġnī"),
    q(646, "Vergleichender Gebetsfiqh", "Al-Fātiḥah hinter dem Imām", "Fortgeschritten",
      "Welche bekannte Meinungsverschiedenheit besteht über die Qurʾān-Rezitation eines Mitbetenden hinter dem Imām?",
      ["Die schāfiʿitische Schule verbietet al-Fātiḥah, während die ḥanafitische Schule sie in jeder Rakʿah verlangt.",
       "Die ḥanafitische Schule lässt den Mitbetenden grundsätzlich nicht hinter dem Imām rezitieren; die schāfiʿitische Schule verlangt al-Fātiḥah grundsätzlich auch vom Mitbetenden.",
       "Alle Schulen erklären die Rezitation des Imāms für ungültig.",
       "Die Frage betrifft ausschließlich freiwillige Nachtgebete."],
      1, "Die ḥanafitische Schule betont das Zuhören und Schweigen des Mitbetenden. In der schāfiʿitischen Schule gehört al-Fātiḥah grundsätzlich zur Rezitationspflicht jedes Betenden, auch hinter dem Imām.",
      "Vergleichender Fiqh", "Al-Marġīnānī, al-Hidāyah, Kitāb aṣ-Ṣalāh; an-Nawawī, al-Maǧmūʿ, Bāb Qirāʾat al-Fātiḥah"),
    q(647, "Ḥadīth-Wissenschaft", "Muʿallaq", "Fortgeschritten",
      "Was kennzeichnet einen muʿallaq überlieferten Bericht?",
      ["Der Text enthält eine zusätzliche Erklärung eines Überlieferers.",
       "Zwei Überlieferer vertauschen versehentlich ihre Namen.",
       "Der Bericht wird von besonders vielen Personen überliefert.",
       "Am Anfang der Überlieferungskette werden ein oder mehrere aufeinanderfolgende Überlieferer ausgelassen."],
      3, "Beim Muʿallaq fehlt vom Beginn der Kette aus mindestens ein Überlieferer. Die bloße Aufnahme eines solchen Berichtes in einem Werk bestimmt noch nicht automatisch seine endgültige Authentizitätsbewertung.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah, Bāb al-Muʿallaq; Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(648, "Ḥadīth-Wissenschaft", "Muʿḍal", "Fortgeschritten",
      "Was ist ein muʿḍal überlieferter Bericht?",
      ["Ein Bericht, in dessen Überlieferungskette mindestens zwei aufeinanderfolgende Überlieferer fehlen.",
       "Ein Bericht, dessen Text ausschließlich aus zwei Sätzen besteht.",
       "Ein Bericht, den zwei Ṣaḥābah gemeinsam überliefern.",
       "Ein Bericht mit zwei vollständig erhaltenen Überlieferungsketten."],
      0, "Der Muʿḍal besitzt eine besonders schwere Form der Kettenunterbrechung, weil zwei oder mehr aufeinanderfolgende Überlieferer ausgelassen wurden.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah, Bāb al-Muʿḍal; as-Suyūṭī, Tadrīb ar-Rāwī"),
    q(649, "Ḥadīth-Wissenschaft", "Mudraǧ", "Fortgeschritten",
      "Was bezeichnet Idrāǧ in einem Ḥadīth?",
      ["Die Überlieferung durch einen besonders hochrangigen Isnād.",
       "Das Kürzen eines Berichts ohne Veränderung seiner Bedeutung.",
       "Das Einfügen von Worten oder Informationen in Isnād oder Matn, die ursprünglich nicht zu diesem Teil des prophetischen Berichtes gehörten.",
       "Die Überlieferung eines Ḥadīths in mehreren Sprachen."],
      2, "Ein Mudraǧ kann entstehen, wenn eine Erklärung eines Überlieferers irrtümlich als Bestandteil des ursprünglichen Ḥadīth-Textes verstanden wird oder wenn Material in die Kette eingefügt erscheint.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah, Bāb al-Mudraǧ; Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(650, "Ḥadīth-Wissenschaft", "Maqlūb", "Fortgeschritten",
      "Was kennzeichnet einen maqlūb überlieferten Bericht?",
      ["Der Bericht besitzt ausschließlich eine sehr kurze Überlieferungskette.",
       "Namen, Zuordnungen oder Formulierungen werden vertauscht beziehungsweise umgekehrt.",
       "Der Bericht wird ausschließlich sinngemäß überliefert.",
       "Der Bericht enthält eine juristische Meinungsverschiedenheit."],
      1, "Beim Maqlūb können beispielsweise Namen zweier Überlieferer vertauscht, eine Kette einem anderen Text zugeordnet oder Teile des Wortlauts umgestellt werden.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah, Bāb al-Maqlūb; Ibn Ḥaǧar, Nuḫbat al-Fikar"),
]

if __name__ == "__main__":
    if len(QUESTIONS) != 25:
        raise SystemExit(f"Expected 25 questions, got {len(QUESTIONS)}")
    expected = list(range(626, 651))
    actual = [q["number"] for q in QUESTIONS]
    if actual != expected:
        raise SystemExit(f"Numbering mismatch: {actual}")
    out = Path(__file__).resolve().parent.parent / "data" / "quiz-batch-626-650.json"
    out.write_text(json.dumps(QUESTIONS, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(QUESTIONS)} questions to {out}")
