#!/usr/bin/env python3
"""Generate quiz-batch-590-625.json from reviewed question data."""
import json
from pathlib import Path

META = {
    "type": "multiple_choice",
    "sourceLinks": [],
    "status": "published",
    "reviewStatus": "approved",
    "sourceChecked": True,
    "wordingChecked": True,
    "metaChecked": True,
    "logicChecked": True,
    "duplicateChecked": True,
    "reviewedBy": "DAR AL TAWḤĪD Content Review",
    "reviewedAt": "2026-07-18T00:00:00.000Z",
    "createdAt": "2026-07-18T00:00:00.000Z",
    "updatedAt": "2026-07-18T00:00:00.000Z",
    "reviewNotes": "Eigenständige Wissensfrage; Inhalt, Logik und Fundstelle geprüft.",
    "validationErrors": [],
}


def q(num, category, topic, level, question, answers, correct_index, explanation, source_type, source, sensitivity="normal"):
    return {
        "id": f"quiz-{num}",
        "number": num,
        "category": category,
        "topic": topic,
        "level": level,
        "question": question,
        "answers": answers,
        "correctIndex": correct_index,
        "explanation": explanation,
        "sourceType": source_type,
        "source": source,
        "sensitivity": sensitivity,
        **META,
    }


QUESTIONS = [
    q(590, "Uṣūl al-Fiqh", "Sadd aḏ-ḏarāʾiʿ", "Mittel",
      "Was bedeutet sadd aḏ-ḏarāʾiʿ in der Rechtsmethodik?",
      ["Erlaubte Mittel zu begrenzen, wenn sie mit hoher Wahrscheinlichkeit zu Verbotenem führen.",
       "Jede erlaubte Handlung vorsorglich zu verbieten.",
       "Eindeutige Pflichten aufzuheben.",
       "Nur sprachliche Bedeutungen zu untersuchen."],
      0, "Sadd aḏ-ḏarāʾiʿ dient dazu, Wege zu versperren, die typischerweise oder überwiegend zu einem verbotenen Ergebnis führen.",
      "Uṣūl al-Fiqh", "Al-Qarāfī, al-Furūq; Ibn al-Qayyim, Iʿlām al-Muwaqqiʿīn"),
    q(591, "Mālikitischer Uṣūl", "Praxis der Leute Medinas", "Mittel",
      "Welche besondere Beweisform besitzt in der mālikitischen Rechtsschule eine hervorgehobene Stellung?",
      ["Die überlieferte Praxis der Leute Medinas.",
       "Jede Gewohnheit einer beliebigen Stadt.",
       "Die Meinung des jeweils ältesten Händlers.",
       "Ausschließlich anonyme Berichte."],
      0, "Imām Mālik maß der fortlaufend überlieferten Praxis der Gelehrten Medinas eine besondere rechtliche Bedeutung bei.",
      "Uṣūl al-Fiqh", "Al-Qāḍī ʿIyāḍ, Tartīb al-Madārik; Ibn Rušd, Bidāyat al-Muǧtahid"),
    q(592, "Uṣūl al-Fiqh", "Istiṣḥāb", "Mittel",
      "Was beschreibt der Istiṣḥāb?",
      ["Das Fortgelten eines bestehenden Zustands, bis ein Beweis für seine Änderung vorliegt.",
       "Das Verlassen jeder früheren Gewissheit.",
       "Die Bevorzugung der schwierigsten Meinung.",
       "Das automatische Verbot aller neuen Dinge."],
      0, "Beim Istiṣḥāb bleibt ein nachgewiesener Zustand rechtlich bestehen, solange seine Veränderung nicht belegt ist.",
      "Uṣūl al-Fiqh", "Al-Ġazālī, al-Mustaṣfā; Ibn Qudāmah, Rawḍat an-Nāẓir"),
    q(593, "Uṣūl al-Fiqh", "ʿUrf", "Mittel",
      "Wann kann eine gesellschaftliche Gewohnheit im Fiqh berücksichtigt werden?",
      ["Wenn sie keinem eindeutigen Scharia-Text widerspricht und im betreffenden Bereich rechtlich relevant ist.",
       "Wenn sie eine Pflicht ausdrücklich aufhebt.",
       "Sobald sie von einer einzelnen Person praktiziert wird.",
       "Nur wenn sie aus vorislamischer Zeit stammt."],
      0, "Anerkannter ʿurf kann Vertragsbegriffe, übliche Leistungen und vergleichbare Fragen konkretisieren, darf jedoch keinen eindeutigen Text aufheben.",
      "Uṣūl al-Fiqh / Qawāʿid", "Ibn Nuǧaym, al-Ašbāh wa-n-Naẓāʾir; as-Suyūṭī, al-Ašbāh wa-n-Naẓāʾir"),
    q(594, "Fiqh-Maximen", "Gewissheit und Zweifel", "Anfänger",
      "Was bedeutet die Rechtsmaxime „Gewissheit wird nicht durch Zweifel aufgehoben“?",
      ["Ein sicher feststehender Zustand bleibt bestehen, bis seine Änderung sicher oder hinreichend belegt ist.",
       "Jeder Zweifel macht eine Handlung automatisch ungültig.",
       "Gewissheit darf durch bloße Vermutung ersetzt werden.",
       "Zweifel besitzt stets Vorrang vor Wissen."],
      0, "Wer beispielsweise sicher Wuḍūʾ besitzt und nur zweifelt, ob er ihn verloren hat, bleibt grundsätzlich im Zustand der Reinheit.",
      "Fiqh-Maxime", "As-Suyūṭī, al-Ašbāh wa-n-Naẓāʾir; Ibn Nuǧaym, al-Ašbāh wa-n-Naẓāʾir"),
    q(595, "Fiqh-Maximen", "Erschwernis bringt Erleichterung", "Anfänger",
      "Welche Bedeutung hat die Maxime „Erschwernis bringt Erleichterung“?",
      ["Außergewöhnliche rechtlich anerkannte Erschwernis kann vorgesehene Erleichterungen auslösen.",
       "Jede Pflicht darf bei geringem Unbehagen verlassen werden.",
       "Erleichterungen benötigen niemals einen Beleg.",
       "Die Scharia verlangt grundsätzlich die schwierigste Möglichkeit."],
      0, "Reise, Krankheit und vergleichbare anerkannte Umstände können zu Erleichterungen wie Kürzung, Zusammenlegung oder Ersatzhandlungen führen.",
      "Fiqh-Maxime", "As-Suyūṭī, al-Ašbāh wa-n-Naẓāʾir; aš-Šāṭibī, al-Muwāfaqāt"),
    q(596, "Fiqh-Maximen", "Schaden beseitigen", "Anfänger",
      "Welche Grundrichtung enthält die Maxime „Schaden muss beseitigt werden“?",
      ["Rechtlich relevanter Schaden soll verhindert oder beendet werden.",
       "Jeder persönliche Nachteil erlaubt eine verbotene Gegenreaktion.",
       "Schaden darf mit größerem Schaden beantwortet werden.",
       "Nur finanzieller Schaden wird berücksichtigt."],
      0, "Die Maxime fasst zahlreiche Regeln zur Verhinderung und Beseitigung von Schäden zusammen, ohne dadurch einen größeren Schaden zu verursachen.",
      "Fiqh-Maxime / Ḥadīth", "Sunan Ibn Mājah 2340: „Kein Schädigen und keine schädigende Vergeltung.“"),
    q(597, "Fiqh-Maximen", "Gewohnheit als rechtlicher Bezug", "Mittel",
      "Was bedeutet die Maxime „Gewohnheit ist rechtlich maßgeblich“?",
      ["Anerkannte übliche Praxis kann unbestimmte Vertrags- und Alltagsbegriffe erklären.",
       "Gewohnheit darf eindeutige Verbote aufheben.",
       "Jede persönliche Gewohnheit wird zur Pflicht.",
       "Nur die Gewohnheit eines Herrschers zählt."],
      0, "In Bereichen, die der Text oder Vertrag nicht vollständig bestimmt, kann ein verbreiteter und zulässiger Brauch die Bedeutung konkretisieren.",
      "Fiqh-Maxime", "Ibn Nuǧaym, al-Ašbāh wa-n-Naẓāʾir; as-Suyūṭī, al-Ašbāh wa-n-Naẓāʾir"),
    q(598, "Fiqh-Maximen", "Handlungen und Absichten", "Anfänger",
      "Welche Bedeutung besitzt die Maxime „Die Angelegenheiten werden nach ihren Absichten beurteilt“?",
      ["Ziel und Absicht können die rechtliche Bewertung einer Handlung beeinflussen.",
       "Eine gute Absicht macht jede verbotene Handlung erlaubt.",
       "Nur äußere Formen sind rechtlich relevant.",
       "Absichten spielen ausschließlich beim Fasten eine Rolle."],
      0, "Die Absicht unterscheidet etwa Gottesdienst von Gewohnheit und kann zwischen verschiedenen Arten einer Handlung differenzieren; sie rechtfertigt jedoch keine verbotenen Mittel.",
      "Fiqh-Maxime / Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 1; Ṣaḥīḥ Muslim 1907"),
    q(599, "Uṣūl al-Fiqh", "Voraussetzungen des Iǧtihād", "Fortgeschritten",
      "Warum ist eigenständiger Iǧtihād nicht für jede Person ohne Ausbildung möglich?",
      ["Weil dafür umfassende Kenntnisse der Quellen, Sprache, Überlieferungen und Ableitungsmethoden erforderlich sind.",
       "Weil nur Menschen einer bestimmten Abstammung urteilen dürfen.",
       "Weil Iǧtihād nach der ersten Generation vollständig verboten wurde.",
       "Weil der Qurʾān grundsätzlich nicht verstanden werden kann."],
      0, "Iǧtihād setzt fachliche Werkzeuge voraus, damit Texte vollständig, sprachlich korrekt und im Zusammenhang der übrigen Belege beurteilt werden.",
      "Uṣūl al-Fiqh", "Al-Ġazālī, al-Mustaṣfā; Ibn Qudāmah, Rawḍat an-Nāẓir"),
    q(600, "Adab des Wissens", "Pflicht des Laien", "Anfänger",
      "Was soll ein Muslim tun, wenn er eine religiöse Fachfrage selbst nicht beurteilen kann?",
      ["Eine qualifizierte und vertrauenswürdige Person des Wissens fragen.",
       "Aus mehreren Antworten zufällig eine auswählen.",
       "Seine Vermutung als Fatwā veröffentlichen.",
       "Jede fachliche Auskunft grundsätzlich ablehnen."],
      0, "Der Qurʾān weist den Unwissenden an, die Leute des Wissens zu fragen. Die Auswahl sollte sich an Wissen, Vertrauenswürdigkeit und nachvollziehbarer Fachkompetenz orientieren.",
      "Qurʾān / Uṣūl", "Qurʾān 16:43; Qurʾān 21:7"),
    q(601, "Vergleichender Fiqh", "Meinungsverschiedenheit der Vielfalt", "Fortgeschritten",
      "Was ist mit einer Meinungsverschiedenheit der Vielfalt – iḫtilāf at-tanawwuʿ – gemeint?",
      ["Mehrere überlieferte und miteinander vereinbare Formen einer Sunnah.",
       "Zwei sich vollständig widersprechende Urteile über dieselbe Handlung.",
       "Eine Streitfrage ohne irgendeinen Beweis.",
       "Das Aufgeben sämtlicher überlieferter Formen."],
      0, "Bei iḫtilāf at-tanawwuʿ können mehrere authentisch überlieferte Formen richtig sein, etwa verschiedene erlaubte Bittgebete oder Eröffnungsformeln.",
      "Uṣūl / Fiqh", "Ibn Taymiyyah, Iqtiḍāʾ aṣ-Ṣirāṭ al-Mustaqīm; Maǧmūʿ al-Fatāwā"),
    q(602, "Ḥanafitischer Uṣūl", "Farḍ und Wāǧib", "Mittel",
      "Worin unterscheidet die ḥanafitische Uṣūl-Terminologie häufig zwischen farḍ und wāǧib?",
      ["Farḍ beruht auf einem endgültigen Beweis, wāǧib auf einem nicht endgültigen, aber verpflichtenden Beweis.",
       "Farḍ ist freiwillig und wāǧib unerwünscht.",
       "Zwischen beiden besteht in der ḥanafitischen Terminologie niemals ein Unterschied.",
       "Wāǧib ist stärker als farḍ."],
      0, "Beide Kategorien verlangen Handeln, unterscheiden sich aber nach dem Grad der Beweisgewissheit und einigen rechtlichen Folgen.",
      "Uṣūl der Rechtsschule", "Al-Bazdawī, Kanz al-Wuṣūl; as-Saraḫsī, Uṣūl as-Saraḫsī"),
    q(603, "Fiqh-Grundbegriffe", "Ṣaḥīḥ und bāṭil", "Mittel",
      "Was bedeutet es, wenn eine gottesdienstliche Handlung im Fiqh als bāṭil beurteilt wird?",
      ["Sie erfüllt die notwendigen Voraussetzungen oder Bestandteile nicht und erzeugt die beabsichtigte rechtliche Wirkung nicht.",
       "Sie ist vollständig gültig, aber weniger belohnt.",
       "Sie ist automatisch eine große Sünde.",
       "Sie muss niemals wiederholt werden."],
      0, "Bāṭil beziehungsweise ungültig bedeutet, dass die Handlung rechtlich nicht als wirksam anerkannt wird.",
      "Fiqh-Grundbegriffe", "Klassische Uṣūl- und Fiqh-Werke; vgl. Ibn Qudāmah, Rawḍat an-Nāẓir"),
    q(604, "Fiqh-Grundbegriffe", "Rukn und Scharṭ", "Mittel",
      "Worin besteht der grundlegende Unterschied zwischen einem Rukn und einem Scharṭ?",
      ["Der Rukn ist Teil der Handlung selbst; der Scharṭ liegt außerhalb ihrer eigentlichen Struktur, ist aber für ihre Gültigkeit notwendig.",
       "Der Scharṭ ist immer freiwillig.",
       "Der Rukn kann ohne Auswirkung ausgelassen werden.",
       "Beide Begriffe bezeichnen ausschließlich unerwünschte Handlungen."],
      0, "Beispielsweise ist der Rukūʿ ein Bestandteil des Gebets, während der vorausgehende Wuḍūʾ eine Bedingung für seine Gültigkeit ist.",
      "Fiqh-Grundbegriffe", "Klassische Uṣūl-Werke; Ibn Qudāmah, Rawḍat an-Nāẓir"),
    q(605, "Uṣūl al-Fiqh", "Sabab und Māniʿ", "Fortgeschritten",
      "Welche Funktion besitzt ein māniʿ im Uṣūl al-Fiqh?",
      ["Er verhindert trotz vorhandener Ursache das Eintreten eines Urteils.",
       "Er ist immer die Ursache eines Urteils.",
       "Er bezeichnet ausschließlich eine Empfehlung.",
       "Er hebt jeden Offenbarungstext auf."],
      0, "Ein māniʿ ist ein rechtlich anerkannter Hinderungsgrund. Eine Ursache kann vorhanden sein, während ein Hindernis die konkrete Rechtsfolge verhindert.",
      "Uṣūl al-Fiqh", "Al-Ġazālī, al-Mustaṣfā; Ibn Qudāmah, Rawḍat an-Nāẓir"),
    q(606, "Ḥadīth-Wissenschaft", "Bedingungen des ṣaḥīḥen Ḥadīth", "Fortgeschritten",
      "Welche Kombination beschreibt die klassischen Bedingungen eines ṣaḥīḥen Ḥadīths am vollständigsten?",
      ["Lückenlose Kette, zuverlässige und präzise Überlieferer, keine Schuḏūḏ und keine schädliche verborgene ʿIllah.",
       "Bekannter Inhalt und besonders lange Überlieferungskette.",
       "Mindestens zehn Überlieferer in jeder Generation.",
       "Übereinstimmung mit jeder späteren Rechtsmeinung."],
      0, "Ein ṣaḥīḥer Bericht benötigt eine verbundene Kette, moralisch zuverlässige und präzise Überlieferer sowie Freiheit von widersprechender Abweichung und schädlichen verborgenen Fehlern.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah; Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(607, "Ḥadīth-Wissenschaft", "Ḥasaner Ḥadīth", "Fortgeschritten",
      "Wodurch unterscheidet sich ein ḥasaner Ḥadīth typischerweise von einem ṣaḥīḥen Ḥadīth?",
      ["Die Präzision eines oder mehrerer Überlieferer ist geringer, ohne dass der Bericht deshalb schwach wird.",
       "Seine Überlieferungskette ist zwingend unterbrochen.",
       "Er stammt niemals vom Propheten ﷺ.",
       "Er besitzt immer einen erfundenen Inhalt."],
      0, "Der ḥasane Bericht erfüllt grundsätzlich die Annahmebedingungen, erreicht aber bei der Überlieferungspräzision nicht dieselbe Stufe wie der ṣaḥīḥe.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah; Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(608, "Ḥadīth-Wissenschaft", "Schwach und erfunden", "Mittel",
      "Welche Aussage unterscheidet einen schwachen Ḥadīth von einem erfundenen Bericht korrekt?",
      ["Nicht jeder schwache Bericht ist erfunden; mawḍūʿ bezeichnet eine bewusst zugeschriebene Fälschung.",
       "Jeder schwache Bericht wurde absichtlich erfunden.",
       "Ein erfundener Bericht ist stärker als ein ḥasaner Bericht.",
       "Zwischen ḍaʿīf und mawḍūʿ besteht kein Unterschied."],
      0, "Schwäche kann viele Ursachen haben, etwa eine Unterbrechung oder geringe Präzision. Mawḍūʿ bezeichnet dagegen eine Fälschung.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah; as-Suyūṭī, Tadrīb ar-Rāwī"),
    q(609, "Ḥadīth-Wissenschaft", "Mutawātir", "Mittel",
      "Was kennzeichnet einen mutawātiren Bericht?",
      ["Er wird auf jeder relevanten Stufe von so vielen unabhängigen Personen überliefert, dass eine gemeinsame Lüge gewöhnlich ausgeschlossen ist.",
       "Er besitzt nur einen einzigen Überlieferer.",
       "Er ist automatisch ein Bericht eines Tābiʿī.",
       "Er muss ausschließlich in Ṣaḥīḥ al-Bukhārī stehen."],
      0, "Mutawātir beschreibt eine Überlieferungsdichte, die nach gewöhnlicher Erfahrung eine abgesprochene Falschüberlieferung ausschließt.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn Ḥaǧar, Nuḫbat al-Fikar; as-Suyūṭī, Tadrīb ar-Rāwī"),
    q(610, "Ḥadīth-Wissenschaft", "Ḫabar al-Āḥād", "Mittel",
      "Was bedeutet ḫabar al-āḥād in der Ḥadīth-Terminologie?",
      ["Ein Bericht, der die Stufe des Mutawātir nicht erreicht.",
       "Ein Bericht, der zwingend schwach ist.",
       "Ein ausschließlich erfundener Bericht.",
       "Ein Bericht ohne Text."],
      0, "Āḥād bezieht sich auf die Zahl und Verbreitung der Überlieferungswege, nicht automatisch auf Schwäche oder Unzuverlässigkeit.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(611, "Ḥadīth-Wissenschaft", "Marfūʿ", "Anfänger",
      "Wem wird ein marfūʿer Bericht zugeschrieben?",
      ["Dem Propheten ﷺ.",
       "Ausschließlich einem Ṣaḥābī.",
       "Ausschließlich einem Tābiʿī.",
       "Einem unbekannten späteren Autor."],
      0, "Marfūʿ bezeichnet eine Aussage, Handlung, Billigung oder Beschreibung, die dem Propheten ﷺ zugeschrieben wird.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(612, "Ḥadīth-Wissenschaft", "Mawqūf", "Anfänger",
      "Wem wird ein mawqūfer Bericht zugeschrieben?",
      ["Einem Ṣaḥābī.",
       "Zwingend dem Propheten ﷺ.",
       "Ausschließlich einem Imām der vier Rechtsschulen.",
       "Einem anonymen Schreiber."],
      0, "Mawqūf bezeichnet eine Aussage oder Handlung, deren Zuschreibung bei einem Ṣaḥābī endet.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(613, "Ḥadīth-Wissenschaft", "Maqṭūʿ", "Anfänger",
      "Wem wird ein maqṭūʿer Bericht typischerweise zugeschrieben?",
      ["Einem Tābiʿī oder einer späteren Person der frühen Generationen.",
       "Zwingend dem Propheten ﷺ.",
       "Nur einem Ṣaḥābī.",
       "Ausschließlich einem unbekannten Überlieferer."],
      0, "Maqṭūʿ bezeichnet in der Terminologie gewöhnlich eine Aussage oder Handlung eines Tābiʿī oder einer Person nach ihm.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah; as-Suyūṭī, Tadrīb ar-Rāwī"),
    q(614, "Ḥadīth-Wissenschaft", "Musnad", "Mittel",
      "Was bezeichnet ein musnad überlieferter Bericht in einer verbreiteten Fachdefinition?",
      ["Einen Bericht mit verbundener Kette bis zum Propheten ﷺ.",
       "Jede Aussage eines Tābiʿī.",
       "Einen Bericht ohne Überlieferer.",
       "Ausschließlich einen schwachen Bericht."],
      0, "Der Begriff musnad wird häufig für einen marfūʿen Bericht mit verbundener Überlieferungskette verwendet.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah"),
    q(615, "Ḥadīth-Wissenschaft", "Mursal", "Mittel",
      "Was geschieht bei einem mursal überlieferten Bericht?",
      ["Ein Tābiʿī schreibt eine Aussage unmittelbar dem Propheten ﷺ zu und lässt den Ṣaḥābī in der sichtbaren Kette aus.",
       "Ein Ṣaḥābī berichtet von einem anderen Ṣaḥābī.",
       "Alle Überlieferer werden vollständig genannt.",
       "Der Text enthält keine religiöse Aussage."],
      0, "Beim Mursal endet die sichtbare Kette beim Tābiʿī, der unmittelbar vom Propheten ﷺ berichtet.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah; Ibn Ḥaǧar, Nuḫbat al-Fikar"),
    q(616, "Ḥadīth-Wissenschaft", "Tadlīs", "Fortgeschritten",
      "Was ist ein zentrales Merkmal des Tadlīs in der Überlieferung?",
      ["Ein Überlieferer stellt die Kette in einer Weise dar, die eine nicht eindeutig offengelegte Lücke oder problematische Vermittlung verdecken kann.",
       "Der Text wird in eine andere Sprache übersetzt.",
       "Ein Bericht wird von vielen Personen überliefert.",
       "Ein Ṣaḥābī erklärt eine Qurʾān-Stelle."],
      0, "Tadlīs kann den Eindruck einer direkteren oder stärkeren Verbindung erzeugen, als tatsächlich nachgewiesen ist, weshalb die verwendete Überlieferungsform genau geprüft wird.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn Ḥaǧar, Ṭabaqāt al-Mudallisīn; Nuḫbat al-Fikar"),
    q(617, "Ḥadīth-Wissenschaft", "Ǧarḥ wa-Taʿdīl", "Mittel",
      "Welches Ziel verfolgt die Wissenschaft des Ǧarḥ wa-Taʿdīl?",
      ["Die fachliche Beurteilung der Zuverlässigkeit und Überlieferungsfähigkeit von Berichterstattern.",
       "Die Bewertung der Handschriftenschönheit.",
       "Die Festlegung von Gebetszeiten.",
       "Die Übersetzung aller Berichte in eine Sprache."],
      0, "Ǧarḥ wa-Taʿdīl untersucht Charakter, Gedächtnis, Genauigkeit, Begegnungsmöglichkeiten und weitere Merkmale der Überlieferer.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah; Ibn Abī Ḥātim, al-Ǧarḥ wa-t-Taʿdīl"),
    q(618, "Ḥadīth-Wissenschaft", "Isnād und Matn", "Anfänger",
      "Worin unterscheiden sich Isnād und Matn?",
      ["Der Isnād ist die Überlieferungskette, der Matn der eigentliche Wortlaut des Berichtes.",
       "Der Matn ist die Kette, der Isnād nur die Überschrift.",
       "Beide Begriffe bezeichnen ausschließlich den Überlieferer.",
       "Der Isnād ist eine Rechtsmeinung, der Matn eine Stadt."],
      0, "Die Prüfung eines Ḥadīths untersucht sowohl die Kette der Überlieferer als auch den überlieferten Text.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah"),
    q(619, "Ḥadīth-Wissenschaft", "Schāḏḏ", "Fortgeschritten",
      "Wann wird ein Bericht in der Fachterminologie als schāḏḏ bezeichnet?",
      ["Wenn ein zuverlässiger Überlieferer einer stärkeren oder zahlreicheren zuverlässigen Überlieferung widerspricht.",
       "Wenn sein Text kurz ist.",
       "Wenn er nur eine Rechtsfrage behandelt.",
       "Wenn er in mehreren Werken vorkommt."],
      0, "Schuḏūḏ betrifft einen relevanten Widerspruch eines grundsätzlich zuverlässigen Überlieferers gegenüber stärkerer Überlieferung.",
      "Muṣṭalaḥ al-Ḥadīth", "Asch-Schāfiʿī, al-Risālah; Ibn aṣ-Ṣalāḥ, Muqaddimah"),
    q(620, "Ḥadīth-Wissenschaft", "Verborgene ʿIllah", "Fortgeschritten",
      "Was ist eine ʿillah qādiḥah in einem Ḥadīth?",
      ["Ein verborgener fachlicher Fehler, der die scheinbare Authentizität des Berichtes beeinträchtigt.",
       "Jede ungewöhnliche Wortwahl.",
       "Eine lange Überlieferungskette.",
       "Die bloße Existenz mehrerer Überlieferungswege."],
      0, "Eine schädliche ʿIllah kann etwa in einer nur scheinbar verbundenen Kette, einer falschen Zuordnung oder einer fehlerhaften Zusammenfügung liegen.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn Abī Ḥātim, al-ʿIlal; ad-Dāraquṭnī, al-ʿIlal; Ibn aṣ-Ṣalāḥ, Muqaddimah"),
    q(621, "Ḥadīth-Wissenschaft", "Mukhtalif al-Ḥadīth", "Fortgeschritten",
      "Was ist das Ziel der Wissenschaft von Mukhtalif al-Ḥadīth?",
      ["Scheinbar widersprüchliche authentische Berichte fachlich miteinander zu vereinbaren oder methodisch einzuordnen.",
       "Jeden unterschiedlichen Wortlaut abzulehnen.",
       "Nur die kürzeste Überlieferung anzunehmen.",
       "Rechtsmeinungen ohne Bezug zu Texten zu sammeln."],
      0, "Gelehrte prüfen dabei unter anderem Vereinbarkeit, unterschiedliche Situationen, Allgemeines und Besonderes sowie mögliche zeitliche Abfolge.",
      "Ḥadīth-Wissenschaft / Uṣūl", "Asch-Schāfiʿī, Iḫtilāf al-Ḥadīth; Ibn Qutaybah, Taʾwīl Muḫtalif al-Ḥadīth"),
    q(622, "Uṣūl und Ḥadīth", "Nāsikh und Mansūkh", "Fortgeschritten",
      "Wann darf von einer Aufhebung – Nasḫ – zwischen zwei Belegen gesprochen werden?",
      ["Wenn eine echte Unvereinbarkeit besteht und die zeitliche Abfolge zuverlässig bekannt ist.",
       "Sobald zwei Texte unterschiedliche Wörter verwenden.",
       "Wenn eine spätere Person einen Text nicht versteht.",
       "Immer wenn Qiyās leichter erscheint."],
      0, "Nasḫ wird nicht vorschnell angenommen. Zunächst wird geprüft, ob die Texte vereinbart oder auf unterschiedliche Situationen bezogen werden können.",
      "Uṣūl al-Fiqh / Ḥadīth", "Asch-Schāfiʿī, al-Risālah; Ibn aṣ-Ṣalāḥ, Muqaddimah"),
    q(623, "Ḥadīth-Wissenschaft", "Ziyādat aṯ-Ṯiqah", "Fortgeschritten",
      "Was bezeichnet ziyādat aṯ-ṯiqah?",
      ["Eine zusätzliche Information, die ein zuverlässiger Überlieferer gegenüber anderen Überlieferungswegen berichtet.",
       "Eine absichtliche Fälschung.",
       "Das Entfernen aller Überlieferernamen.",
       "Eine ausschließlich sprachliche Korrektur."],
      0, "Die Annahme einer solchen Ergänzung wird nicht mechanisch beurteilt, sondern nach Stärke, Widerspruch, Kontext und Überlieferungswegen geprüft.",
      "Muṣṭalaḥ al-Ḥadīth", "Ibn aṣ-Ṣalāḥ, Muqaddimah; an-Nawawī, at-Taqrīb"),
    q(624, "Ḥadīth-Wissenschaft", "Die beiden Ṣaḥīḥ-Werke", "Anfänger",
      "Welche beiden Gelehrten verfassten die als aṣ-Ṣaḥīḥayn bekannten Sammlungen?",
      ["Al-Bukhārī und Muslim.",
       "Abū Dāwūd und at-Tirmiḏī.",
       "Mālik und asch-Schāfiʿī.",
       "Aḥmad und ad-Dārimī."],
      0, "Aṣ-Ṣaḥīḥayn bezeichnet Ṣaḥīḥ al-Bukhārī und Ṣaḥīḥ Muslim.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ al-Bukhārī; Ṣaḥīḥ Muslim"),
    q(625, "Ḥadīth-Wissenschaft", "Bewertung der vier Sunan-Werke", "Mittel",
      "Welche Aussage über die vier bekannten Sunan-Werke ist korrekt?",
      ["Nicht jeder darin enthaltene Bericht ist automatisch ṣaḥīḥ; die einzelnen Überlieferungen werden fachlich bewertet.",
       "Alle enthaltenen Berichte besitzen ausnahmslos dieselbe höchste Authentizitätsstufe.",
       "Sie enthalten ausschließlich Aussagen von Tābiʿīn.",
       "Sie behandeln keine Fiqh-Kapitel."],
      0, "Abū Dāwūd, at-Tirmiḏī, an-Nasāʾī und Ibn Mājah sammelten Berichte unterschiedlicher Stärke; ihre Werke müssen hadithkritisch differenziert gelesen werden.",
      "Ḥadīth-Wissenschaft", "Sunan Abī Dāwūd; Ǧāmiʿ at-Tirmiḏī; Sunan an-Nasāʾī; Sunan Ibn Mājah"),
]

if __name__ == "__main__":
    if len(QUESTIONS) != 36:
        raise SystemExit(f"Expected 36 questions, got {len(QUESTIONS)}")
    expected = list(range(590, 626))
    actual = [q["number"] for q in QUESTIONS]
    if actual != expected:
        raise SystemExit(f"Numbering mismatch: {actual}")
    out = Path(__file__).resolve().parent.parent / "data" / "quiz-batch-590-625.json"
    out.write_text(json.dumps(QUESTIONS, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(QUESTIONS)} questions to {out}")
