#!/usr/bin/env python3
"""Generate quiz-batch-526-625.json from reviewed question data."""
import json
from pathlib import Path

META = {
    "type": "multiple_choice",
    "sourceLinks": [],
    "status": "published",
    "reviewStatus": "approved",
    "sourceChecked": True,
    "wordingChecked": True,
    "metaChecked": True,
    "logicChecked": True,
    "duplicateChecked": True,
    "reviewedBy": "DAR AL TAWḤĪD Content Review",
    "reviewedAt": "2026-07-18T00:00:00.000Z",
    "createdAt": "2026-07-18T00:00:00.000Z",
    "updatedAt": "2026-07-18T00:00:00.000Z",
    "reviewNotes": "Eigenständige Wissensfrage; Inhalt, Logik und Fundstelle geprüft.",
    "validationErrors": [],
}


def q(num, category, topic, level, question, answers, correct_index, explanation, source_type, source, sensitivity="normal"):
    return {
        "id": f"quiz-{num}",
        "number": num,
        "category": category,
        "topic": topic,
        "level": level,
        "question": question,
        "answers": answers,
        "correctIndex": correct_index,
        "explanation": explanation,
        "sourceType": source_type,
        "source": source,
        "sensitivity": sensitivity,
        **META,
    }


QUESTIONS = [
    q(526, "Wissen", "Verlust der Amānah", "Mittel",
      "Woran erkennt man gemäß dem Ḥadīth einen schweren Verlust der Amānah vor der Stunde?",
      ["Daran, dass Wissen nur noch schriftlich vermittelt wird.",
       "Daran, dass Verantwortung ungeeigneten Personen übertragen wird.",
       "Daran, dass Menschen weniger reisen.",
       "Daran, dass jede politische Aufgabe abgeschafft wird."],
      1, "Der Prophet ﷺ erklärte, dass die Amānah verloren geht, wenn Angelegenheiten Menschen übertragen werden, die dafür nicht geeignet sind.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 59", "sensitive"),
    q(527, "Adab des Wissens", "Eine Frage geordnet beantworten", "Mittel",
      "Wie ging der Prophet ﷺ vor, als während eines laufenden Gesprächs eine neue Frage gestellt wurde?",
      ["Er brach jede Erklärung sofort ab.", "Er ignorierte den Fragenden dauerhaft.",
       "Er beendete zunächst seine laufende Erklärung und beantwortete danach die Frage.",
       "Er verbot Fragen in Versammlungen."],
      2, "Der Bericht zeigt geordnetes Lehren: Der Prophet ﷺ vollendete seine laufende Erklärung und wandte sich anschließend dem Fragenden zu.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 59"),
    q(528, "Ṭahārah", "Fersen beim Wuḍūʾ", "Anfänger",
      "Welche Körperstelle wurde im Ḥadīth besonders gewarnt, wenn sie beim Wuḍūʾ nicht richtig gewaschen wird?",
      ["Die Ellbogen.", "Die Fersen.", "Die Ohren.", "Die Stirn."],
      1, "Als einige ihre Füße nur unvollständig benetzten, warnte der Prophet ﷺ eindringlich vor ungewaschenen Fersen.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 60"),
    q(529, "Wissen", "Gleichnis des Muslims", "Anfänger",
      "Mit welchem Baum verglich der Prophet ﷺ den Muslim?",
      ["Mit dem Olivenbaum.", "Mit der Dattelpalme.", "Mit dem Feigenbaum.", "Mit der Zeder."],
      1, "Der Prophet ﷺ verglich den Muslim mit der Dattelpalme, deren Blätter nicht abfallen.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 61"),
    q(530, "Adab des Wissens", "Schüchternheit beim Antworten", "Mittel",
      "Was hinderte den jungen Ibn ʿUmar رضي الله عنهما daran, die Dattelpalme als Lösung des Gleichnisses zu nennen?",
      ["Er kannte die Antwort nicht.", "Er war nicht anwesend.",
       "Er war aus Respekt und Schüchternheit zurückhaltend.", "Er hielt die Frage für unzulässig."],
      2, "Ibn ʿUmar hatte die richtige Antwort erkannt, schwieg jedoch aus Schüchternheit in Gegenwart älterer Gefährten.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 61"),
    q(531, "Sīrah", "Allgemeinheit der Sendung", "Anfänger",
      "Welche Aussage bestätigte der Prophet ﷺ gegenüber Ḍimām ibn Thaʿlabah über seine Sendung?",
      ["Er sei nur zu Quraysh gesandt worden.", "Er sei zu allen Menschen gesandt worden.",
       "Er sei nur zu den Bewohnern Madīnahs gesandt worden.", "Seine Botschaft gelte nur für eine Generation."],
      1, "Ḍimām fragte, ob الله den Propheten ﷺ zu allen Menschen gesandt habe; der Prophet bestätigte dies.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 63"),
    q(532, "Gebet", "Fünf Pflichtgebete", "Anfänger",
      "Wie viele Gebete am Tag und in der Nacht bestätigte der Prophet ﷺ gegenüber Ḍimām als verpflichtend?",
      ["Drei.", "Vier.", "Fünf.", "Sieben."],
      2, "Der Prophet ﷺ bestätigte die Verpflichtung der fünf täglichen Gebete.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 63"),
    q(533, "Ṣawm / Fasten", "Pflichtfasten", "Anfänger",
      "Welches jährliche Fasten bestätigte der Prophet ﷺ im Gespräch mit Ḍimām ibn Thaʿlabah?",
      ["Den gesamten Monat Muḥarram.", "Den Monat Ramaḍān.", "Jeden Montag.", "Die ersten zehn Tage jedes Monats."],
      1, "Der Bericht nennt das Fasten des Monats Ramaḍān als verpflichtendes jährliches Fasten.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 63"),
    q(534, "Zakāh", "Verteilung der Zakāh", "Anfänger",
      "Wie beschrieb Ḍimām ibn Thaʿlabah die Verteilung der verpflichtenden Abgabe?",
      ["Sie wird von den Armen genommen und den Reichen gegeben.", "Sie wird ausschließlich für Gebäude verwendet.",
       "Sie wird von den Reichen genommen und unter den Armen verteilt.", "Sie bleibt vollständig beim Einsammler."],
      2, "Der Prophet ﷺ bestätigte, dass die verpflichtende Abgabe von den Wohlhabenden genommen und den Bedürftigen gegeben wird.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 63"),
    q(535, "Sīrah", "Schriftliche Daʿwah", "Mittel",
      "Über welchen Herrscher gelangte der Brief des Propheten ﷺ schließlich zu Kisrā?",
      ["Über den Herrscher von Bahrain.", "Über den Herrscher von Ägypten.",
       "Über den Herrscher von Jemen.", "Über den Herrscher von Abessinien."],
      0, "Der Brief wurde zunächst dem Herrscher von Bahrain übergeben, der ihn an Kisrā weiterleitete.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 64"),
    q(536, "Sīrah", "Versiegelung von Briefen", "Mittel",
      "Warum ließ der Prophet ﷺ einen Siegelring anfertigen?",
      ["Weil Herrscher unversiegelte Briefe nicht lasen.", "Weil Schmuck für Männer verpflichtend war.",
       "Weil jeder Brief aus Silber bestehen musste.", "Weil der Ring als Zahlungsmittel diente."],
      0, "Dem Propheten ﷺ wurde mitgeteilt, dass Herrscher nur versiegelte Schreiben annahmen; deshalb ließ er einen Siegelring anfertigen.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 65"),
    q(537, "Sīrah", "Inschrift des Siegelrings", "Mittel",
      "Welche Inschrift trug der Siegelring des Propheten ﷺ?",
      ["Muḥammad ibn ʿAbdillāh.", "Muḥammad Rasūl الله.", "Lā ilāha illa الله allein.", "Al-Madīnah al-Munawwarah."],
      1, "Auf dem silbernen Siegelring stand „Muḥammad Rasūl الله“.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 65"),
    q(538, "Daʿwah", "Erleichterung beim Lehren", "Anfänger",
      "Welche doppelte Anweisung gab der Prophet ﷺ beim Vermitteln des Dīn?",
      ["Erschwert und warnt ohne Hoffnung.", "Erleichtert und gebt frohe Botschaft, ohne abzuschrecken.",
       "Schweigt grundsätzlich über Pflichten.", "Sprecht nur zu Gelehrten."],
      1, "Die Vermittlung soll wahrheitsgemäß, verständlich und nicht unnötig abschreckend erfolgen.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 69"),
    q(539, "Adab des Wissens", "Geeignete Zeiten für Ermahnung", "Mittel",
      "Warum hielt Ibn Masʿūd رضي الله عنه seine Ermahnungen nicht täglich?",
      ["Er wollte die Menschen nicht langweilen oder überfordern.", "Er besaß nur an einem Tag Wissen.",
       "Er hielt tägliches Lehren für verboten.", "Er durfte ausschließlich donnerstags sprechen."],
      0, "Ibn Masʿūd wählte passende Zeiten für Ermahnungen, wie es der Prophet ﷺ getan hatte, damit die Menschen nicht ermüdeten.",
      "Athar / Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 70"),
    q(540, "Wissen", "Fiqh im Dīn", "Anfänger",
      "Welche Gabe ist gemäß dem Ḥadīth ein Zeichen dafür, dass الله einem Menschen Gutes will?",
      ["Vollständige Freiheit von Prüfungen.", "Verständnis im Dīn.", "Großer gesellschaftlicher Einfluss.", "Zahlreiche Anhänger."],
      1, "Der Prophet ﷺ erklärte, dass الله demjenigen, für den Er Gutes will, Verständnis im Dīn gibt.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 71"),
    q(541, "Tazkiyah", "Lobenswerter Wetteifer mit Vermögen", "Mittel",
      "Bei welcher Verwendung von Vermögen ist lobenswerter Wetteifer gemäß dem Ḥadīth zulässig?",
      ["Wenn Vermögen nur gesammelt wird.", "Wenn es im Recht und für gute Zwecke ausgegeben wird.",
       "Wenn es der Selbstdarstellung dient.", "Wenn damit andere herabgesetzt werden."],
      1, "Der Ḥadīth nennt denjenigen, dem الله Vermögen gibt und der es rechtmäßig ausgibt.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 73"),
    q(542, "Wissen", "Lobenswerter Wetteifer mit Weisheit", "Mittel",
      "Welche zwei Handlungen zeichnen den Besitzer von Weisheit im Ḥadīth aus?",
      ["Er verbirgt sie und spricht nie darüber.", "Er urteilt danach und lehrt sie andere.",
       "Er verwendet sie nur für weltliche Ziele.", "Er lehnt jede Weitergabe ab."],
      1, "Lobenswerter Wetteifer gilt auch für jemanden, dem Weisheit gegeben wurde, der danach urteilt und sie lehrt.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 73"),
    q(543, "Ṣaḥābah", "Duʿāʾ für Ibn ʿAbbās", "Anfänger",
      "Welche besondere Gabe erbat der Prophet ﷺ für Ibn ʿAbbās رضي الله عنهما?",
      ["Reichtum.", "Kenntnis des Buches.", "Führung eines Heeres.", "Langes Reisen."],
      1, "Der Prophet ﷺ bat الله darum, Ibn ʿAbbās das Buch zu lehren.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 75"),
    q(544, "Adab des Wissens", "Überlieferung eines Jugendlichen", "Mittel",
      "Welcher Umstand zeigt im Bericht von Ibn ʿAbbās, dass auch die Beobachtung eines Jugendlichen berücksichtigt werden kann?",
      ["Er war nahe am Pubertätsalter und erinnerte sich an das Geschehen in Minā.", "Er hatte bereits ein Richteramt.",
       "Er war älter als alle Anwesenden.", "Er berichtete nur aus einem Buch."],
      0, "Ibn ʿAbbās berichtete ein Ereignis, das er kurz vor dem Pubertätsalter selbst erlebt hatte.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 76"),
    q(545, "Adab des Wissens", "Frühe Erinnerung", "Anfänger",
      "Wie alt war Maḥmūd ibn ar-Rabīʿ ungefähr bei dem Ereignis, an das er sich vom Propheten ﷺ erinnerte?",
      ["Drei Jahre.", "Fünf Jahre.", "Zehn Jahre.", "Fünfzehn Jahre."],
      1, "Maḥmūd berichtete, er habe sich an dieses Ereignis erinnert, als er fünf Jahre alt war.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 77"),
    q(546, "Wissen", "Mūsā und al-Khiḍr", "Mittel",
      "Warum machte sich Mūsā عليه السلام auf den Weg zu al-Khiḍr?",
      ["Weil ihm mitgeteilt wurde, dass al-Khiḍr Wissen besaß, das er lernen sollte.", "Weil er einen politischen Auftrag erhielt.",
       "Weil er sein Volk verlassen wollte.", "Weil al-Khiḍr ihn zu einem Wettkampf herausforderte."],
      0, "Als Mūsā erfuhr, dass ein Diener اللهs Wissen besaß, das ihm nicht gegeben war, suchte er den Weg zu ihm.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 78"),
    q(547, "Wissen", "Zeichen für den Treffpunkt", "Mittel",
      "Welches Zeichen sollte Mūsā عليه السلام zum Ort der Begegnung mit al-Khiḍr führen?",
      ["Das Verschwinden eines Fisches.", "Das Erlöschen eines Feuers.", "Das Auftauchen eines Vogels.", "Ein plötzlich einsetzender Regen."],
      0, "Der verlorene Fisch war das Zeichen für den Ort, an dem Mūsā al-Khiḍr treffen würde.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 78"),
    q(548, "Zeichen der Stunde", "Abnahme des Wissens", "Mittel",
      "Welche Entwicklung wird im Ḥadīth als Zeichen der Stunde genannt?",
      ["Religiöses Wissen nimmt ab und Unwissenheit breitet sich aus.", "Jeder Mensch wird automatisch Gelehrter.",
       "Streit und Unwissenheit verschwinden vollständig.", "Überlieferungen werden nicht mehr benötigt."],
      0, "Zu den Zeichen der Stunde gehören die Abnahme des Wissens und die Verbreitung religiöser Unwissenheit.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 81", "sensitive"),
    q(549, "Wissen", "Traumsymbol Milch", "Mittel",
      "Was symbolisierte die Milch im Traum des Propheten ﷺ, deren Rest er ʿUmar رضي الله عنه gab?",
      ["Vermögen.", "Wissen.", "Politische Macht.", "Eine Reise."],
      1, "Der Prophet ﷺ deutete die Milch in diesem Traum als religiöses Wissen.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 82"),
    q(550, "Fiqh", "Reihenfolge der Ḥajj-Riten", "Mittel",
      "Wie antwortete der Prophet ﷺ auf vergessene Vertauschungen bestimmter Ḥajj-Riten am Opfertag?",
      ["Der gesamte Ḥajj müsse wiederholt werden.", "Die Person müsse sofort nach Hause zurückkehren.",
       "Die versäumte Handlung solle nachgeholt werden, ohne dass darin eine Bedrängnis liege.",
       "Jede Reihenfolge sei bewusst ohne Einschränkung beliebig."],
      2, "Bei versehentlichen Vertauschungen wie Rasieren vor dem Schlachten antwortete der Prophet ﷺ: Führe die Handlung aus; es besteht keine Bedrängnis.",
      "Ṣaḥīḥ Ḥadīth", "Ṣaḥīḥ al-Bukhārī 83"),
    q(551, "Ḥadīth-Wissenschaft", "Wenige sichere Berichte", "Fortgeschritten",
      "Welche Vorgehensweise hielt Imām Muslim für gewöhnliche Lernende für vorrangig?",
      ["Viele schwache Berichte zu sammeln.", "Wenige authentische Berichte sicher zu beherrschen.",
       "Nur außergewöhnliche Berichte zu suchen.", "Auf jede Prüfung der Überlieferer zu verzichten."],
      1, "Imām Muslim erklärte, dass die sichere Beherrschung weniger authentischer Berichte wertvoller ist als die Menge schwacher Überlieferungen.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(552, "Ḥadīth-Wissenschaft", "Erste Stufe der Überlieferer", "Fortgeschritten",
      "Welche Eigenschaften kennzeichnen bei Imām Muslim die höchste zuerst berücksichtigte Gruppe von Überlieferern?",
      ["Unbekanntheit und außergewöhnliche Formulierungen.", "Integrität, Genauigkeit und geringe Widersprüchlichkeit.",
       "Große Zahl von Schülern ohne Prüfung.", "Ausschließlich hohes Alter."],
      1, "Imām Muslim stellte Berichte von Überlieferern voran, die für Integrität, Präzision und geringe Fehlerhaftigkeit bekannt waren.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(553, "Ḥadīth-Wissenschaft", "Stufen vertrauenswürdiger Überlieferer", "Fortgeschritten",
      "Welche methodische Erkenntnis verdeutlicht Imām Muslims Vergleich verschiedener grundsätzlich wahrhaftiger Überlieferer?",
      ["Alle wahrhaftigen Überlieferer besitzen exakt dieselbe Stufe.",
       "Zwischen Wahrhaftigen können deutliche Unterschiede in Präzision und Rang bestehen.",
       "Präzision spielt keine Rolle.", "Nur die Herkunft entscheidet über den Rang."],
      1, "Auch unter ehrlichen Überlieferern gibt es Unterschiede in Gedächtnis, Genauigkeit und Zuverlässigkeit.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(554, "Ḥadīth-Wissenschaft", "Gerechte Rangordnung", "Fortgeschritten",
      "Welche Regel nennt Imām Muslim beim Einstufen von Trägern des Wissens?",
      ["Jeder wird über seine tatsächliche Stufe erhoben.",
       "Der Hochrangige wird nicht herabgesetzt und der Niedrigere nicht über seine Stufe erhoben.",
       "Nur bekannte Namen werden berücksichtigt.", "Jede Kritik ist grundsätzlich verboten."],
      1, "Jeder Wissenträger soll entsprechend seinem tatsächlichen Rang behandelt werden, ohne Überhöhung oder ungerechte Herabsetzung.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(555, "Ḥadīth-Wissenschaft", "Erkennung munkarer Berichte", "Fortgeschritten",
      "Woran kann ein munkarer Bericht nach Imām Muslims Erklärung erkannt werden?",
      ["Er stimmt mit den präzisen Überlieferern überein.",
       "Er widerspricht den Berichten zuverlässiger und anerkannter Überlieferer.",
       "Er besitzt eine kurze Überlieferungskette.", "Er behandelt ein bekanntes Thema."],
      1, "Eine starke Abweichung von den Berichten zuverlässiger Bewahrer ist ein wesentliches Zeichen für einen munkaren Bericht.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(556, "Ḥadīth-Wissenschaft", "Überlieferer mit vielen Fehlern", "Fortgeschritten",
      "Wie wird ein Überlieferer behandelt, dessen Berichte überwiegend munkar oder fehlerhaft sind?",
      ["Seine Berichte werden ohne Einschränkung angenommen.", "Er wird in der Ḥadīth-Überlieferung verlassen.",
       "Nur seine längsten Berichte werden bevorzugt.", "Sein gesellschaftlicher Rang hebt die Fehler auf."],
      1, "Wenn schwere Widersprüche und Fehler den Großteil seiner Überlieferungen bestimmen, werden seine Berichte nicht als Grundlage angenommen.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(557, "Ḥadīth-Wissenschaft", "Zusatz eines zuverlässigen Überlieferers", "Fortgeschritten",
      "Unter welcher Voraussetzung kann ein zusätzlicher Inhalt eines einzelnen Überlieferers angenommen werden?",
      ["Wenn er gewöhnlich mit zuverlässigen Überlieferern übereinstimmt und selbst anerkannt ist.",
       "Wenn er sonst niemals mit zuverlässigen Überlieferern übereinstimmt.",
       "Wenn der Zusatz besonders erstaunlich klingt.", "Wenn keine Überlieferungskette vorhanden ist."],
      0, "Imām Muslim erklärt, dass der Zusatz eines grundsätzlich zuverlässigen und meist übereinstimmenden Überlieferers angenommen werden kann.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(558, "Ḥadīth-Wissenschaft", "Unbekannter Einzelbericht", "Fortgeschritten",
      "Warum wird ein unbekannter Einzelbericht von einem berühmten Lehrer kritisch betrachtet, wenn ihn keiner seiner bekannten Schüler überliefert?",
      ["Weil berühmte Lehrer keine Schüler besitzen.",
       "Weil eine solche Abweichung ohne Stütze Zweifel an der Überlieferung weckt.",
       "Weil Einzelberichte grundsätzlich immer falsch sind.", "Weil nur schriftliche Berichte erlaubt sind."],
      1, "Bei einem weithin überlieferten Lehrer ist ein isolierter, bei seinen bekannten Schülern unbekannter Bericht besonders prüfungsbedürftig.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah"),
    q(559, "Ḥadīth-Wissenschaft", "Schwache Berichte für Laien", "Fortgeschritten",
      "Welche Gefahr sah Imām Muslim in der Verbreitung schwacher und verwerflicher Berichte unter unkundigen Menschen?",
      ["Sie erkennen automatisch alle Fehler.", "Sie können die Mängel nicht einordnen und werden dadurch irregeführt.",
       "Sie werden dadurch zu Ḥadīth-Kritikern.", "Schwache Berichte werden durch Verbreitung authentisch."],
      1, "Unkundige Menschen können verborgene Mängel nicht erkennen; deshalb ist das wahllose Verbreiten schwacher Berichte gefährlich.",
      "Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah", "sensitive"),
    q(560, "Ṣaḥābah", "Ibn ʿAbbās prüft ein Schriftstück", "Fortgeschritten",
      "Was tat Ibn ʿAbbās رضي الله عنهما mit einem Schriftstück, das angebliche Urteile ʿAlīs رضي الله عنه enthielt?",
      ["Er veröffentlichte es vollständig.", "Er löschte fast alles daraus und ließ nur einen kleinen Teil stehen.",
       "Er erklärte jede Zeile ohne Prüfung für authentisch.", "Er übergab es einem Herrscher."],
      1, "Der Bericht zeigt, wie entschieden Ibn ʿAbbās unzuverlässige Zuschreibungen zu ʿAlī zurückwies.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 23", "sensitive"),
    q(561, "Ṣaḥābah", "Verfälschung zugeschriebenen Wissens", "Fortgeschritten",
      "Wie reagierte ein Gefährte ʿAlīs رضي الله عنه auf später erfundene Zuschreibungen?",
      ["Er lobte ihre Vielzahl.", "Er beklagte, dass dadurch Wissen verdorben wurde.",
       "Er hielt Zuschreibungen ohne Kette für unproblematisch.", "Er sammelte sie ohne Prüfung."],
      1, "Der Gefährte beklagte, dass die erfundenen Zuschreibungen verschiedene Bereiche des Wissens verdorben hätten.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 24", "sensitive"),
    q(562, "Ḥadīth-Wissenschaft", "Berichte von ʿAlī", "Fortgeschritten",
      "Über welche Gruppe galten nach al-Mughīrah zuverlässige Berichte von ʿAlī رضي الله عنه als bestätigt?",
      ["Über unbekannte spätere Erzähler.", "Über die Gefährten von ʿAbdullāh ibn Masʿūd.",
       "Nur über Herrscher.", "Ausschließlich über Familienmitglieder ʿAlīs."],
      1, "Al-Mughīrah hob die Vertrauenswürdigkeit der Wege über die Gefährten Ibn Masʿūds hervor.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 25"),
    q(563, "Salaf", "Bedingung für die Annahme eines Berichts", "Mittel",
      "Welche Bedingung stellte Ṭāwūs für die Annahme eines übermittelten Berichts?",
      ["Der Überlieferer muss vertrauenswürdig sein.", "Der Bericht muss ungewöhnlich lang sein.",
       "Der Überlieferer muss aus Makkah stammen.", "Der Bericht muss viele unbekannte Namen enthalten."],
      0, "Ṭāwūs riet zur Annahme eines Berichts, wenn der Überlieferer als vertrauenswürdig bekannt ist.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 28"),
    q(564, "Ḥadīth-Wissenschaft", "Vertrauenswürdig, aber kein Fachmann", "Fortgeschritten",
      "Warum wurde von manchen persönlich vertrauenswürdigen Menschen in Madīnah dennoch kein Ḥadīth genommen?",
      ["Sie gehörten nicht zu den Fachleuten der Überlieferung.", "Sie waren zu alt.",
       "Sie besaßen keine Häuser.", "Sie kannten keine Händler."],
      0, "Abū az-Zinād unterschied zwischen persönlicher Vertrauenswürdigkeit und fachlicher Eignung zur Ḥadīth-Überlieferung.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 30"),
    q(565, "Ḥadīth-Wissenschaft", "Nur von Vertrauenswürdigen überliefern", "Mittel",
      "Von welchen Personen soll nach Saʿd ibn Ibrāhīm über den Gesandten اللهs ﷺ berichtet werden?",
      ["Von vertrauenswürdigen Überlieferern.", "Von jedem, der überzeugend spricht.",
       "Nur von politisch einflussreichen Personen.", "Von Unbekannten, wenn der Inhalt beliebt ist."],
      0, "Saʿd ibn Ibrāhīm erklärte, dass nur vertrauenswürdige Überlieferer Berichte vom Propheten ﷺ weitergeben sollen.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 31"),
    q(566, "Ḥadīth-Wissenschaft", "Isnād als Teil des Dīn", "Mittel",
      "Warum bezeichnete Ibn al-Mubārak den Isnād als Teil des Dīn?",
      ["Weil ohne Überlieferungskette jeder behaupten könnte, was er wollte.", "Weil nur sehr lange Ketten gültig sind.",
       "Weil Namen wichtiger als Inhalte sind.", "Weil jede Kette automatisch authentisch ist."],
      0, "Die Überlieferungskette ermöglicht die Prüfung einer Zuschreibung und schützt vor beliebigen Behauptungen.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 32", "sensitive"),
    q(567, "Ḥadīth-Wissenschaft", "Die tragenden Säulen", "Fortgeschritten",
      "Was meinte Ibn al-Mubārak mit der Aussage: „Zwischen uns und den Leuten stehen die tragenden Säulen“?",
      ["Die Mauern der Moschee.", "Die Überlieferungsketten.", "Die politischen Grenzen.", "Die Stammeslisten."],
      1, "Mit den tragenden Säulen meinte Ibn al-Mubārak die Isnād-Ketten, durch die Behauptungen geprüft werden.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 32"),
    q(568, "Ḥadīth-Wissenschaft", "Erkennen einer unterbrochenen Kette", "Fortgeschritten",
      "Welchen Mangel erkannte Ibn al-Mubārak in einem Bericht, der direkt von al-Ḥajjāj ibn Dīnār zum Propheten ﷺ führte?",
      ["Zwischen dem Erzähler und dem Propheten ﷺ fehlten Überlieferer.", "Der Text war zu kurz.",
       "Der Bericht enthielt keine Rechtsfrage.", "Der Erzähler war aus Madīnah."],
      0, "Ibn al-Mubārak machte deutlich, dass zwischen al-Ḥajjāj ibn Dīnār und dem Propheten ﷺ eine große Lücke in der Kette bestand.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 32"),
    q(569, "Manhaj", "Beschimpfung der Salaf", "Fortgeschritten",
      "Warum riet Ibn al-Mubārak, die Überlieferungen von ʿAmr ibn Thābit zu verlassen?",
      ["Weil er die Salaf beschimpfte.", "Weil er keine Reisen unternahm.",
       "Weil er nur kurze Berichte erzählte.", "Weil er aus Kūfah stammte."],
      0, "Ibn al-Mubārak verband die Verlässlichkeit eines Überlieferers auch mit seiner Haltung gegenüber den Salaf.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 32", "sensitive"),
    q(570, "Adab des Wissens", "Schwerer als Nichtwissen", "Mittel",
      "Was hielt al-Qāsim ibn ʿUbaydillāh für schlimmer, als eine Frage nicht beantworten zu können?",
      ["Ohne Wissen zu sprechen oder von einem Unzuverlässigen zu berichten.", "Eine Antwort aufzuschieben.",
       "Einen Gelehrten zu fragen.", "Eine Quelle zu prüfen."],
      0, "Al-Qāsim erklärte, dass ehrliches Nichtwissen sicherer ist als unbelegtes Sprechen oder unzuverlässige Überlieferung.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 33"),
    q(571, "Adab des Wissens", "Abstammung ersetzt kein Wissen", "Mittel",
      "Welche Lehre ergibt sich aus der Antwort al-Qāsims, obwohl er von zwei Imamen der Rechtleitung abstammte?",
      ["Edle Abstammung erlaubt Antworten ohne Wissen.", "Auch hohe Abstammung ersetzt keine tatsächliche Kenntnis.",
       "Nur Nachkommen bekannter Familien dürfen schweigen.", "Abstammung ist die wichtigste Quelle einer Fatwā."],
      1, "Al-Qāsim wies zurück, dass seine Abstammung ihn zum Sprechen ohne Wissen berechtige.",
      "Athar", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 33"),
    q(572, "Ḥadīth-Wissenschaft", "Warnung vor unzuverlässigen Erzählern", "Fortgeschritten",
      "Was empfahlen Sufyān ath-Thawrī, Shuʿbah, Mālik und Ibn ʿUyaynah über einen nicht zuverlässigen Überlieferer?",
      ["Seinen Zustand den Fragenden offen mitzuteilen.", "Seinen Zustand ausnahmslos zu verschweigen.",
       "Seine Berichte wegen seiner Bekanntheit anzunehmen.", "Nur seine längsten Berichte zu übernehmen."],
      0, "Die Imame betrachteten die sachliche Warnung vor einem unzuverlässigen Erzähler als Schutz der Überlieferung.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 35", "sensitive"),
    q(573, "Ḥadīth-Wissenschaft", "Kritik an Schahr", "Fortgeschritten",
      "Wie beschrieb Ibn ʿAwn den Zustand der Überlieferungen Schahrs?",
      ["Die Fachleute hatten ihn kritisiert.", "Es bestand vollständige Einigkeit über höchste Präzision.",
       "Seine Berichte benötigten keine Prüfung.", "Niemand hatte je über ihn gesprochen."],
      0, "Ibn ʿAwn verwies darauf, dass die Fachleute Schahr in der Überlieferung kritisiert hatten.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 36"),
    q(574, "Ḥadīth-Wissenschaft", "Shuʿbahs Entscheidung", "Fortgeschritten",
      "Welche Entscheidung traf Shuʿbah nach seiner Begegnung mit Schahr?",
      ["Er machte ihn zu seinem wichtigsten Lehrer.", "Er verzichtete darauf, von ihm zu überliefern.",
       "Er erklärte alle seine Berichte für mutawātir.", "Er schrieb ausschließlich seine Rechtsmeinungen auf."],
      1, "Shuʿbah berichtete, dass er Schahr getroffen, seine Überlieferungen aber nicht als Grundlage genommen habe.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 37"),
    q(575, "Ḥadīth-Wissenschaft", "Dīn und Überlieferungskompetenz unterscheiden", "Fortgeschritten",
      "Wie unterschied Ibn al-Mubārak bei ʿAbbād ibn Kathīr zwischen persönlichem Dīn und Überlieferungskompetenz?",
      ["Er lobte seinen Dīn, warnte aber davor, Ḥadīth von ihm zu nehmen.",
       "Er erklärte guten Charakter für ausreichend zur Annahme aller Berichte.",
       "Er verwarf jede gute Eigenschaft des Mannes.", "Er verbot jede sachliche Beurteilung."],
      0, "Ein Mensch kann persönlich fromm erscheinen und dennoch für die Ḥadīth-Überlieferung ungeeignet sein.",
      "Athar / Ḥadīth-Wissenschaft", "Ṣaḥīḥ Muslim, Muqaddimah, Introduction 38", "sensitive"),
    q(576, "Qurʾān", "Umfassende Rechtschaffenheit", "Mittel",
      "Welche Aussage beschreibt al-Birr gemäß Qurʾān 2:177 am vollständigsten?",
      ["Nur die Gebetsrichtung bestimmt Rechtschaffenheit.",
       "Glaube, Gottesdienst, Hilfe für Bedürftige, Vertragstreue und Geduld gehören gemeinsam dazu.",
       "Nur freiwillige Spenden gehören dazu.", "Abstammung ist der entscheidende Maßstab."],
      1, "Der Vers verbindet Glaubensgrundlagen mit Gottesdienst, sozialer Verantwortung, Vertragstreue und Geduld.",
      "Qurʾān", "Qurʾān 2:177"),
    q(577, "Tazkiyah", "Geben trotz Liebe zum Besitz", "Mittel",
      "Welche innere Prüfung nennt Qurʾān 2:177 beim Ausgeben von Vermögen?",
      ["Man gibt nur, was wertlos ist.", "Man gibt Vermögen trotz der eigenen Liebe dazu.",
       "Man gibt ausschließlich öffentlich.", "Man gibt nur an Verwandte."],
      1, "Der Vers lobt das Geben von Vermögen trotz der eigenen Liebe zum Besitz.",
      "Qurʾān", "Qurʾān 2:177"),
    q(578, "Tazkiyah", "Geduld in drei Lagen", "Mittel",
      "In welchen Situationen werden die Wahrhaftigen in Qurʾān 2:177 für Geduld gelobt?",
      ["Nur bei Krankheit.", "In Armut, Bedrängnis und Zeiten des Kampfes.",
       "Nur während einer Reise.", "Nur bei materiellem Verlust."],
      1, "Der Vers nennt Geduld in Not, Bedrängnis und schweren Auseinandersetzungen.",
      "Qurʾān", "Qurʾān 2:177"),
    q(579, "Qurʾān-Wissenschaft", "Klare und mehrdeutige Verse", "Fortgeschritten",
      "Welches Verhalten schreibt Qurʾān 3:7 Menschen mit Abweichung im Herzen gegenüber mehrdeutigen Versen zu?",
      ["Sie folgen ihnen, um Fitnah und eigene Deutung zu suchen.", "Sie richten alles an den klaren Versen aus.",
       "Sie vermeiden jede Aussage ohne Wissen.", "Sie fragen ausschließlich vertrauenswürdige Gelehrte."],
      0, "Der Vers warnt davor, mehrdeutige Texte gezielt zur Fitnah und eigenwilligen Deutung zu verfolgen.",
      "Qurʾān", "Qurʾān 3:7", "sensitive"),
    q(580, "Daʿwah", "Sanftmut in der Führung", "Mittel",
      "Welche Wirkung hatte die Sanftmut des Propheten ﷺ gemäß Qurʾān 3:159?",
      ["Die Menschen versammelten sich nur aus Angst.", "Sie verhinderte, dass die Menschen sich von ihm zerstreuten.",
       "Sie hob jede Pflicht auf.", "Sie machte Beratung überflüssig."],
      1, "Der Vers erklärt, dass Härte die Menschen zerstreut hätte, während Sanftmut sie zusammenhielt.",
      "Qurʾān", "Qurʾān 3:159"),
    q(581, "Manhaj", "Beratung", "Mittel",
      "Welche Vorgehensweise wird dem Propheten ﷺ in Qurʾān 3:159 bei gemeinschaftlichen Angelegenheiten befohlen?",
      ["Allein nach persönlicher Vorliebe zu entscheiden.", "Die Gefährten zu beraten und danach auf الله zu vertrauen.",
       "Nur die wohlhabendsten Menschen zu fragen.", "Jede Entscheidung dauerhaft aufzuschieben."],
      1, "Der Vers verbindet Schūrā mit Entschlusskraft und Tawakkul.",
      "Qurʾān", "Qurʾān 3:159"),
    q(582, "Adab", "Vertrauensgüter zurückgeben", "Anfänger",
      "Welche Pflicht nennt Qurʾān 4:58 hinsichtlich anvertrauter Güter und Aufgaben?",
      ["Sie den Berechtigten zurückzugeben.", "Sie dem Stärksten zu überlassen.",
       "Sie nach persönlicher Nähe zu verteilen.", "Sie ohne Dokumentation zu behalten."],
      0, "Der Vers befiehlt, anvertraute Dinge ihren rechtmäßigen Besitzern beziehungsweise Berechtigten zu übergeben.",
      "Qurʾān", "Qurʾān 4:58"),
    q(583, "Adab", "Gerechtes Urteil", "Anfänger",
      "Wie soll gemäß Qurʾān 4:58 zwischen Menschen geurteilt werden?",
      ["Nach gesellschaftlichem Rang.", "Mit Gerechtigkeit.", "Nach persönlicher Sympathie.", "Nach wirtschaftlichem Nutzen."],
      1, "Der Vers befiehlt ein gerechtes Urteil zwischen Menschen.",
      "Qurʾān", "Qurʾān 4:58"),
    q(584, "Manhaj", "Sicherheitsrelevante Nachrichten", "Fortgeschritten",
      "Was sollen Gläubige gemäß Qurʾān 4:83 mit Nachrichten über Sicherheit oder Gefahr tun?",
      ["Sie sofort ungeprüft verbreiten.", "Sie an den Gesandten und die zuständigen Autoritäten zurückgeben.",
       "Sie vollständig erfinden.", "Sie nur in anonymen Gruppen teilen."],
      1, "Der Vers kritisiert vorschnelle Verbreitung und fordert die Rückgabe an Personen, die den Sachverhalt richtig beurteilen können.",
      "Qurʾān", "Qurʾān 4:83", "sensitive"),
    q(585, "Adab", "Gerechtigkeit trotz Abneigung", "Mittel",
      "Was darf Abneigung gegen eine Gruppe gemäß Qurʾān 5:8 nicht bewirken?",
      ["Dass man ihre Sprache lernt.", "Dass man ungerecht handelt.", "Dass man Beweise prüft.", "Dass man Verträge einhält."],
      1, "Der Vers befiehlt Gerechtigkeit selbst gegenüber Menschen, gegen die starke Abneigung besteht.",
      "Qurʾān", "Qurʾān 5:8"),
    q(586, "Adab", "Schutz menschlichen Lebens", "Mittel",
      "Wie beschreibt Qurʾān 5:32 die Rettung eines Menschenlebens?",
      ["Als Handlung ohne besonderen Wert.", "Wie die Rettung der gesamten Menschheit.",
       "Nur als politische Pflicht.", "Als ausschließlich medizinische Aufgabe."],
      1, "Der Vers hebt den gewaltigen Wert des Schutzes eines unschuldigen Lebens hervor.",
      "Qurʾān", "Qurʾān 5:32"),
    q(587, "Daʿwah", "Keine Beleidigung fremder Heiligtümer", "Fortgeschritten",
      "Warum verbietet Qurʾān 6:108, die von anderen angerufenen falschen Gottheiten zu beschimpfen?",
      ["Damit sie nicht aus Unwissenheit und Feindseligkeit الله beschimpfen.", "Weil jede Religion gleichermaßen wahr ist.",
       "Weil Tawḥīd nicht erklärt werden darf.", "Weil Kritik an falscher Anbetung grundsätzlich verboten ist."],
      0, "Der Vers unterscheidet zwischen sachlicher Widerlegung und einer Beschimpfung, die nur größere Lästerung provoziert.",
      "Qurʾān", "Qurʾān 6:108", "sensitive"),
    q(588, "Manhaj", "Mehrheit ist kein Beweis", "Fortgeschritten",
      "Welche Warnung enthält Qurʾān 6:116 bezüglich der Mehrheit der Menschen?",
      ["Eine Mehrheit kann von اللهs Weg abführen, wenn sie Vermutungen folgt.", "Eine Mehrheit ist immer rechtgeleitet.",
       "Wahrheit wird ausschließlich durch Zahlen bestimmt.", "Minderheiten besitzen niemals Beweise."],
      0, "Der Vers zeigt, dass bloße Zahl und verbreitete Vermutung kein Wahrheitsmaßstab sind.",
      "Qurʾān", "Qurʾān 6:116", "sensitive"),
    q(589, "Adab", "Maßhalten beim Essen und Trinken", "Anfänger",
      "Welche Grenze setzt Qurʾān 7:31 beim Essen und Trinken?",
      ["Man soll vollständig darauf verzichten.", "Man soll nicht verschwenderisch sein.",
       "Man soll nur in der Öffentlichkeit essen.", "Man soll stets mehr nehmen als benötigt."],
      1, "Der Vers erlaubt Essen und Trinken, verbietet jedoch Verschwendung und Maßlosigkeit.",
      "Qurʾān", "Qurʾān 7:31"),
    q(590, "Manhaj", "Folgen des Streits", "Mittel",
      "Welche Folge nennt Qurʾān 8:46 für Streit und Uneinigkeit?",
      ["Streit erhöht automatisch die Standhaftigkeit.", "Mut und Kraft können schwinden.",
       "Jede Auseinandersetzung führt zu Wissen.", "Streit besitzt keine gemeinschaftlichen Folgen."],
      1, "Der Vers verbindet Gehorsam und Standhaftigkeit mit der Warnung, dass Streit Kraft und Entschlossenheit schwächt.",
      "Qurʾān", "Qurʾān 8:46"),
    q(591, "Adab", "Mit den Wahrhaftigen sein", "Anfänger",
      "Mit wem sollen die Gläubigen gemäß Qurʾān 9:119 sein?",
      ["Mit den Wahrhaftigen.", "Mit den Lautesten.", "Mit den Reichsten.", "Mit den zahlenmäßig Größten."],
      0, "Der Vers verbindet Taqwā mit der Gemeinschaft der Wahrhaftigen.",
      "Qurʾān", "Qurʾān 9:119"),
    q(592, "Wissen", "Vermutung und Wahrheit", "Mittel",
      "Welchen Wert besitzt bloße Vermutung gegenüber der Wahrheit gemäß Qurʾān 10:36?",
      ["Sie ersetzt sichere Kenntnis.", "Sie nützt gegenüber der Wahrheit nichts.",
       "Sie ist stärker als Offenbarung.", "Sie genügt immer für religiöse Urteile."],
      1, "Der Vers warnt davor, Vermutungen wie sichere Wahrheit zu behandeln.",
      "Qurʾān", "Qurʾān 10:36"),
    q(593, "Tazkiyah", "Standhaftigkeit ohne Überschreitung", "Mittel",
      "Welche doppelte Anweisung enthält Qurʾān 11:112?",
      ["Bleibe standhaft und überschreite nicht das Maß.", "Verlasse die Offenbarung und folge Gewohnheiten.",
       "Handle nur nach gesellschaftlichem Druck.", "Vermeide jede Verantwortung."],
      0, "Der Vers befiehlt Standhaftigkeit auf dem geraden Weg und warnt zugleich vor Überschreitung.",
      "Qurʾān", "Qurʾān 11:112"),
    q(594, "Wissen", "Über jedem Wissenden", "Anfänger",
      "Welche Aussage über menschliches Wissen enthält Qurʾān 12:76?",
      ["Jeder Wissende besitzt das höchste mögliche Wissen.", "Über jedem Wissenden steht einer, der mehr weiß.",
       "Wissen kann nicht wachsen.", "Nur Könige besitzen Wissen."],
      1, "Der Vers erzieht zur Demut: Menschliches Wissen bleibt begrenzt und über jedem Wissenden steht ein noch Wissenderer.",
      "Qurʾān", "Qurʾān 12:76"),
    q(595, "Tazkiyah", "Veränderung einer Gemeinschaft", "Mittel",
      "Wann verändert الله gemäß Qurʾān 13:11 den Zustand eines Volkes?",
      ["Wenn es selbst verändert, was in ihm ist.", "Ausschließlich nach einem Ortswechsel.",
       "Wenn es jede Verantwortung abweist.", "Nur durch materiellen Wohlstand."],
      0, "Der Vers verbindet äußere Veränderung mit innerer und praktischer Veränderung der Menschen.",
      "Qurʾān", "Qurʾān 13:11"),
    q(596, "Tazkiyah", "Dankbarkeit und Zunahme", "Anfänger",
      "Welche Verheißung enthält Qurʾān 14:7 für Dankbarkeit?",
      ["Dankbarkeit führt zur Zunahme.", "Dankbarkeit mindert jede Gabe.",
       "Dankbarkeit ist nur bei Wohlstand nötig.", "Dankbarkeit besitzt keine Auswirkung."],
      0, "الله verheißt den Dankbaren eine Zunahme Seiner Gaben.",
      "Qurʾān", "Qurʾān 14:7"),
    q(597, "Adab", "Gerechtigkeit und Iḥsān", "Anfänger",
      "Welche drei positiven Pflichten nennt Qurʾān 16:90 gemeinsam?",
      ["Gerechtigkeit, Iḥsān und Geben an Verwandte.", "Stolz, Härte und Rücksichtslosigkeit.",
       "Verschwendung, Streit und Vermutung.", "Schweigen, Isolation und Besitzanhäufung."],
      0, "Der Vers befiehlt Gerechtigkeit, Iḥsān und Unterstützung naher Verwandter.",
      "Qurʾān", "Qurʾān 16:90"),
    q(598, "Daʿwah", "Weisheit in der Einladung", "Mittel",
      "Mit welchen Mitteln soll gemäß Qurʾān 16:125 zum Weg des Herrn eingeladen werden?",
      ["Mit Weisheit, guter Ermahnung und der besten Form der Diskussion.", "Mit Beschimpfung und Demütigung.",
       "Mit ungeprüften Behauptungen.", "Ausschließlich mit politischen Mitteln."],
      0, "Der Vers legt Weisheit, gute Ermahnung und eine sachlich beste Gesprächsweise fest.",
      "Qurʾān", "Qurʾān 16:125"),
    q(599, "Adab", "Verschwendung vermeiden", "Mittel",
      "Welche Menschen bezeichnet Qurʾān 17:27 als Brüder der Shayāṭīn?",
      ["Die Reisenden.", "Die Verschwender.", "Die Bedürftigen.", "Diejenigen, die Verwandten helfen."],
      1, "Der Vers warnt scharf vor verschwenderischem Umgang mit Besitz.",
      "Qurʾān", "Qurʾān 17:26–27"),
    q(600, "Adab", "Würde der Kinder Ādams", "Anfänger",
      "Welche besondere Stellung nennt Qurʾān 17:70 für die Kinder Ādams?",
      ["Sie wurden geehrt.", "Sie wurden ohne Verantwortung erschaffen.",
       "Sie besitzen Kenntnis des Verborgenen.", "Sie sind unabhängig von الله."],
      0, "Der Vers erklärt, dass الله die Kinder Ādams geehrt und ihnen zahlreiche Gaben gegeben hat.",
      "Qurʾān", "Qurʾān 17:70"),
    q(601, "Tazkiyah", "Mit den Aufrichtigen bleiben", "Mittel",
      "Bei welchen Menschen soll der Prophet ﷺ gemäß Qurʾān 18:28 geduldig bleiben?",
      ["Bei denen, die morgens und abends ihren Herrn anrufen und Sein Angesicht suchen.",
       "Nur bei Menschen mit großem Vermögen.", "Nur bei gesellschaftlich einflussreichen Personen.",
       "Bei denen, die ausschließlich das Diesseits suchen."],
      0, "Der Vers lehrt, aufrichtige Gottesdiener nicht zugunsten weltlichen Glanzes zu verlassen.",
      "Qurʾān", "Qurʾān 18:28"),
    q(602, "Dunyā & Ākhirah", "Bleibende gute Taten", "Anfänger",
      "Was ist gemäß Qurʾān 18:46 bei الله besser als bloßer Besitz und Kinder?",
      ["Bleibende gute Taten.", "Gesellschaftlicher Ruhm.", "Eine große Zahl von Anhängern.", "Teure Gebäude."],
      0, "Besitz und Kinder sind Schmuck des Diesseits; bleibende gute Taten sind besser an Lohn und Hoffnung.",
      "Qurʾān", "Qurʾān 18:46"),
    q(603, "Wissen", "Bitte um Wissenszuwachs", "Anfänger",
      "Welche Bitte wird dem Propheten ﷺ in Qurʾān 20:114 gelehrt?",
      ["Mein Herr, mehre mich an Wissen.", "Mein Herr, erspare mir jede Prüfung.",
       "Mein Herr, gib mir mehr Besitz als allen anderen.", "Mein Herr, mache jede Frage leicht."],
      0, "Der Vers lehrt ausdrücklich die Bitte um Zunahme an Wissen.",
      "Qurʾān", "Qurʾān 20:114"),
    q(604, "ʿAqīdah", "Ehrung der Zeichen اللهs", "Mittel",
      "Woraus entsteht gemäß Qurʾān 22:32 die Ehrung der Zeichen اللهs?",
      ["Aus der Taqwā der Herzen.", "Aus Stammesstolz.", "Aus öffentlicher Bekanntheit.", "Aus materieller Überlegenheit."],
      0, "Der Vers verbindet die Ehrung der Zeichen اللهs mit der Gottesfurcht im Herzen.",
      "Qurʾān", "Qurʾān 22:32"),
    q(605, "Gebet", "Khushūʿ im Gebet", "Anfänger",
      "Welche Eigenschaft nennt Qurʾān 23:2 für erfolgreiche Gläubige im Gebet?",
      ["Demut und innere Sammlung.", "Eile und Unruhe.", "Lautes Sprechen.", "Ablenkung durch Handel."],
      0, "Zu den Eigenschaften der erfolgreichen Gläubigen gehört Khushūʿ im Gebet.",
      "Qurʾān", "Qurʾān 23:1–2"),
    q(606, "Adab", "Unnützes meiden", "Anfänger",
      "Wie verhalten sich die erfolgreichen Gläubigen gemäß Qurʾān 23:3 gegenüber nutzlosem Gerede?",
      ["Sie wenden sich davon ab.", "Sie verbreiten es weiter.", "Sie machen es zum Mittelpunkt ihrer Zeit.", "Sie erklären es zu Wissen."],
      0, "Der Vers lobt das Abwenden von laghw, also unnützem und leerem Gerede.",
      "Qurʾān", "Qurʾān 23:3"),
    q(607, "Adab", "Bewahrung der Keuschheit", "Mittel",
      "Welche Grenze nennen Qurʾān 23:5–7 hinsichtlich sexueller Beziehungen?",
      ["Sie sind nur innerhalb der erlaubten Beziehung zulässig.",
       "Jede Beziehung ist erlaubt, solange sie verborgen bleibt.",
       "Persönliche Wünsche bestimmen allein die Grenze.", "Gesellschaftliche Zustimmung ersetzt die Offenbarung."],
      0, "Die Verse loben das Bewahren der Scham und begrenzen sexuelle Beziehungen auf den erlaubten Rahmen.",
      "Qurʾān", "Qurʾān 23:5–7"),
    q(608, "Adab", "Amānah und Verträge", "Anfänger",
      "Welche Eigenschaft erfolgreicher Gläubiger nennen Qurʾān 23:8?",
      ["Sie achten ihre anvertrauten Güter und Verpflichtungen.", "Sie brechen Verträge bei persönlichem Vorteil.",
       "Sie geben Geheimnisse ohne Grund weiter.", "Sie halten nur schriftliche Versprechen."],
      0, "Der Vers lobt die Wahrung von Amānah und Vereinbarungen.",
      "Qurʾān", "Qurʾān 23:8"),
    q(609, "Gebet", "Gebete bewahren", "Anfänger",
      "Welche Haltung zu den Gebeten nennen Qurʾān 23:9?",
      ["Die Gläubigen bewahren ihre Gebete.", "Sie verrichten sie nur bei freier Zeit.",
       "Sie ersetzen sie durch gute Absichten.", "Sie legen ihre Zeiten selbst fest."],
      0, "Der Vers nennt die sorgfältige Bewahrung der Gebete als Eigenschaft erfolgreicher Gläubiger.",
      "Qurʾān", "Qurʾān 23:9"),
    q(610, "Adab", "Vergeben und übersehen", "Mittel",
      "Welche Haltung fordert Qurʾān 24:22 von Menschen, die auf die Vergebung اللهs hoffen?",
      ["Sie sollen vergeben und übersehen.", "Sie sollen jeden Fehler dauerhaft öffentlich machen.",
       "Sie sollen jede Hilfe einstellen.", "Sie sollen Verwandtschaftsrechte aufheben."],
      0, "Der Vers verbindet die Hoffnung auf اللهs Vergebung mit eigener Bereitschaft zu Vergebung und Nachsicht.",
      "Qurʾān", "Qurʾān 24:22"),
    q(611, "Adab", "Erlaubnis vor dem Betreten", "Anfänger",
      "Was muss gemäß Qurʾān 24:27 vor dem Betreten fremder Häuser geschehen?",
      ["Erlaubnis erbitten und die Bewohner grüßen.", "Ohne Ankündigung eintreten.",
       "Nur an die Tür klopfen und sofort eintreten.", "Ausschließlich eine Nachricht hinterlassen."],
      0, "Der Vers schützt Privatsphäre und lehrt Erlaubnis sowie Salām vor dem Eintritt.",
      "Qurʾān", "Qurʾān 24:27"),
    q(612, "Familie", "Drei Zeiten besonderer Privatsphäre", "Mittel",
      "Welche Zeiten nennt Qurʾān 24:58 als besondere Zeiten, zu denen Kinder und Bedienstete um Erlaubnis bitten sollen?",
      ["Vor dem Fajr, während der Mittagsruhe und nach dem ʿIschāʾ.", "Nur nach dem Maghrib.",
       "Ausschließlich während des Ramaḍān.", "Nur vor dem Ẓuhr."],
      0, "Der Vers nennt drei Zeiten, in denen gewöhnlich private Kleidung abgelegt wird und besondere Erlaubnis erforderlich ist.",
      "Qurʾān", "Qurʾān 24:58"),
    q(613, "Adab", "Haltung der Diener des Allerbarmers", "Anfänger",
      "Wie reagieren die Diener des Allerbarmers gemäß Qurʾān 25:63, wenn Unwissende sie grob ansprechen?",
      ["Sie antworten mit friedlichen Worten.", "Sie erwidern jede Beleidigung doppelt.",
       "Sie suchen sofort Streit.", "Sie verbreiten die Beleidigung weiter."],
      0, "Der Vers verbindet Demut im Auftreten mit friedlicher Reaktion auf Unwissenheit.",
      "Qurʾān", "Qurʾān 25:63"),
    q(614, "Adab", "Falschheit meiden", "Mittel",
      "Welche Haltung zu falschem Zeugnis nennt Qurʾān 25:72?",
      ["Die Diener اللهs nehmen nicht daran teil.", "Sie unterstützen es bei persönlichem Nutzen.",
       "Sie halten jede Aussage für gleichwertig.", "Sie verbreiten es, wenn es beliebt ist."],
      0, "Der Vers lobt diejenigen, die Falschheit nicht bezeugen und an leerem Gerede würdevoll vorbeigehen.",
      "Qurʾān", "Qurʾān 25:72"),
    q(615, "Dunyā & Ākhirah", "Ausgewogene Nutzung des Diesseits", "Mittel",
      "Welche Balance lehrt Qurʾān 28:77 im Umgang mit weltlichen Gaben?",
      ["Mit ihnen das Jenseits suchen, ohne den erlaubten Anteil am Diesseits zu vergessen.",
       "Das Jenseits vollständig vergessen.", "Alle erlaubten weltlichen Dinge verbieten.",
       "Besitz ausschließlich zur Selbstdarstellung nutzen."],
      0, "Der Vers richtet weltliche Mittel auf das Jenseits aus, ohne erlaubte Bedürfnisse des Diesseits zu leugnen.",
      "Qurʾān", "Qurʾān 28:77"),
    q(616, "Tazkiyah", "Anstrengung für الله", "Mittel",
      "Welche Verheißung enthält Qurʾān 29:69 für diejenigen, die sich aufrichtig für الله bemühen?",
      ["الله führt sie auf Seine Wege.", "Sie werden nie wieder geprüft.",
       "Sie erhalten automatisch weltliche Macht.", "Sie benötigen keine Offenbarung mehr."],
      0, "Aufrichtige Anstrengung auf dem Weg اللهs wird mit Führung auf Seine Wege verbunden.",
      "Qurʾān", "Qurʾān 29:69"),
    q(617, "Adab", "Keine Überheblichkeit", "Anfänger",
      "Welche körperliche Geste des Hochmuts verbietet Luqmān seinem Sohn in Qurʾān 31:18?",
      ["Den Menschen verächtlich die Wange zuzuwenden.", "Beim Gehen nach unten zu schauen.",
       "Beim Reden die Hände zu bewegen.", "Älteren den Vortritt zu lassen."],
      0, "Luqmān warnt vor verächtlicher Abwendung und überheblichem Auftreten.",
      "Qurʾān", "Qurʾān 31:18"),
    q(618, "Adab", "Maßvolle Stimme", "Anfänger",
      "Welche Anweisung gibt Luqmān in Qurʾān 31:19 zur Stimme?",
      ["Die Stimme zu mäßigen.", "Immer lauter als andere zu sprechen.",
       "Nur flüsternd zu reden.", "Nie öffentlich zu sprechen."],
      0, "Luqmān verbindet maßvolles Gehen mit einer gesenkten, nicht schrillen Stimme.",
      "Qurʾān", "Qurʾān 31:19"),
    q(619, "Sunnah", "Vorbild des Gesandten", "Anfänger",
      "Für wen ist der Gesandte اللهs ﷺ gemäß Qurʾān 33:21 ein ausgezeichnetes Vorbild?",
      ["Für denjenigen, der auf الله und den Jüngsten Tag hofft und الله häufig gedenkt.",
       "Nur für seine direkten Verwandten.", "Nur für Bewohner Madīnahs.", "Nur für Menschen ohne Verantwortung."],
      0, "Der Vers bindet die Vorbildfunktion des Propheten ﷺ an Hoffnung auf الله, den Jüngsten Tag und häufigen Dhikr.",
      "Qurʾān", "Qurʾān 33:21"),
    q(620, "Wissen", "Wissende und Unwissende", "Anfänger",
      "Welche rhetorische Frage stellt Qurʾān 39:9 über Wissen?",
      ["Sind diejenigen, die wissen, denjenigen gleich, die nicht wissen?",
       "Ist Vermögen wichtiger als Wissen?", "Sind alle Meinungen automatisch richtig?", "Ist Wissen nur für frühere Völker?"],
      0, "Der Vers verneint die Gleichstellung von Wissenden und Unwissenden.",
      "Qurʾān", "Qurʾān 39:9"),
    q(621, "Adab des Wissens", "Dem Besten folgen", "Mittel",
      "Welche Eigenschaft besitzen die in Qurʾān 39:18 Gelobten?",
      ["Sie hören Aussagen an und folgen dem Besten davon.", "Sie übernehmen jede Aussage ungeprüft.",
       "Sie folgen immer der lautesten Person.", "Sie lehnen jede Beratung ab."],
      0, "Der Vers lobt Menschen, die aufmerksam zuhören und dem Besten und Wahrsten folgen.",
      "Qurʾān", "Qurʾān 39:18"),
    q(622, "Adab", "Schlechtes mit Besserem abwehren", "Mittel",
      "Welche Wirkung kann entstehen, wenn Schlechtes gemäß Qurʾān 41:34 mit dem Besseren abgewehrt wird?",
      ["Ein Feind kann zu einem engen Freund werden.", "Jede Feindschaft muss sofort mit Härte beantwortet werden.",
       "Gutes Verhalten besitzt keine Wirkung.", "Alle Unterschiede verschwinden ohne weiteres Handeln."],
      0, "Der Vers zeigt, dass edles Verhalten Feindschaft in Nähe und Freundschaft verwandeln kann.",
      "Qurʾān", "Qurʾān 41:34"),
    q(623, "Manhaj", "Schūrā als Eigenschaft der Gläubigen", "Mittel",
      "Wie regeln die Gläubigen gemäß Qurʾān 42:38 ihre gemeinsamen Angelegenheiten?",
      ["Durch gegenseitige Beratung.", "Ausschließlich durch spontane Einzelentscheidungen.",
       "Durch Gerüchte.", "Nur nach wirtschaftlichem Vorteil."],
      0, "Schūrā wird im Vers als feste Eigenschaft der Gläubigen genannt.",
      "Qurʾān", "Qurʾān 42:38"),
    q(624, "Tazkiyah", "Sich nicht selbst für rein erklären", "Mittel",
      "Welche Warnung enthält Qurʾān 53:32 hinsichtlich der eigenen Frömmigkeit?",
      ["Erklärt euch nicht selbst für rein; الله kennt den Gottesfürchtigen am besten.",
       "Jeder soll seine Taten öffentlich loben.", "Menschen können ihre endgültige Stellung sicher bestimmen.",
       "Taqwā wird allein an äußerem Auftreten erkannt."],
      0, "Der Vers verbietet Selbstüberhöhung und erinnert daran, dass الله die tatsächliche Taqwā kennt.",
      "Qurʾān", "Qurʾān 53:32"),
    q(625, "Adab", "Worte ohne Taten", "Anfänger",
      "Welche Handlung wird in Qurʾān 61:2–3 scharf getadelt?",
      ["Etwas zu sagen, das man selbst nicht tut.", "Eine Verpflichtung zuverlässig einzuhalten.",
       "Einen Fehler einzugestehen.", "Wissen mit Beleg weiterzugeben."],
      0, "Der Vers tadelt die Trennung zwischen behaupteten Worten und tatsächlichem Handeln.",
      "Qurʾān", "Qurʾān 61:2–3"),
]

if __name__ == "__main__":
    out = Path(__file__).resolve().parent.parent / "data" / "quiz-batch-526-625.json"
    out.write_text(json.dumps(QUESTIONS, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(QUESTIONS)} questions to {out}")
