#!/usr/bin/env python3
"""Patch offline download client logic in index.html and test/index.html."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = [ROOT / "test/index.html", ROOT / "index.html"]

CSS_ADD = ".offline-resume-btn{margin-top:4px;min-height:36px;padding:6px 12px;border-radius:999px;border:1px solid var(--line);background:rgba(239,215,142,.12);color:var(--cream);font-size:11px;font-weight:800;cursor:pointer}"

REPLACEMENTS = [
    (
        'let offlinePrepUiState={running:false,total:0,loaded:0,failed:0,bytes:0,percent:0,updatedAt:null,status:"idle"};',
        'let offlinePrepUiState={running:false,total:0,loaded:0,failed:0,bytes:0,percent:0,updatedAt:null,status:"idle"};const OFFLINE_PREP_STALE_MS=90000;function offlinePrepIsStale(){const s=readOfflinePrepState();if(!s.running)return false;const ts=Date.parse(s.updatedAt||"");return!Number.isFinite(ts)||(Date.now()-ts)>OFFLINE_PREP_STALE_MS}function repairOfflinePrepState(){const s=readOfflinePrepState();if(s.running&&offlinePrepIsStale()){writeOfflinePrepState({running:false,status:s.percent>=90?"done":(s.percent>0?"partial":"idle")});return true}if(s.status==="error"&&(s.percent||0)>=70){writeOfflinePrepState({running:false,status:"partial"});return true}return false}function offlinePrepShouldResume(){const s=readOfflinePrepState();if(s.running&&!offlinePrepIsStale())return false;return s.status==="partial"||s.status==="error"||(s.percent>0&&s.percent<100)}',
    ),
    (
        'function renderOfflineStatusLine(){const s=readOfflinePrepState();const stamp=s.updatedAt?new Date(s.updatedAt).toLocaleString("de-DE"):"-";if(!navigator.onLine)return`Offline · Stand vom ${stamp}`;if(s.running)return"Online · Inhalte werden geprüft";if(s.status==="done")return`Aktuell · zuletzt synchronisiert um ${stamp}`;return"Online · Offline-Paket bereit zum Aktualisieren"}',
        'function renderOfflineStatusLine(){const s=readOfflinePrepState();const stamp=s.updatedAt?new Date(s.updatedAt).toLocaleString("de-DE"):"-";if(!navigator.onLine)return`Offline · Stand vom ${stamp}`;if(s.running)return"Online · Inhalte werden geprüft";if(s.status==="partial")return`Fast fertig · ${s.loaded||0}/${s.total||0} Dateien · Download fortsetzen`;if(s.status==="done")return`Aktuell · zuletzt synchronisiert um ${stamp}`;return"Online · Offline-Paket bereit zum Aktualisieren"}',
    ),
    (
        'function offlineProgressHtml(){const s=readOfflinePrepState();if(!s.running&&s.status!=="done"&&s.status!=="error")return"";const p=Math.max(0,Math.min(100,Number(s.percent||0)));return `<div class="offline-prep-progress"><div><b>${s.running?"Offline-Paket wird vorbereitet":"Offline-Paket Status"}</b><span>${s.loaded||0}/${s.total||0} Dateien · ${p}% · ${storageBytesLabel(s.bytes)}</span></div><div class="offline-prep-bar"><span style="width:${p}%"></span></div>${s.failed?`<small>${s.failed} Dateien konnten nicht geladen werden.</small>`:""}</div>`}',
        'function offlineProgressHtml(){const s=readOfflinePrepState();if(!s.running&&s.status!=="done"&&s.status!=="error"&&s.status!=="partial")return"";const p=Math.max(0,Math.min(100,Number(s.percent||0)));const label=s.running?"Offline-Paket wird vorbereitet":s.status==="partial"?"Offline-Paket fast fertig":"Offline-Paket Status";const resumeBtn=s.status==="partial"||s.status==="error"?" <button type=\\"button\\" class=\\"offline-resume-btn\\" id=\\"offlineResumeBtn\\">Download fortsetzen</button>":"";return `<div class="offline-prep-progress"><div><b>${label}</b><span>${s.loaded||0}/${s.total||0} Dateien · ${p}% · ${storageBytesLabel(s.bytes)}</span>${resumeBtn}</div><div class="offline-prep-bar"><span style="width:${p}%"></span></div>${s.failed?`<small>${s.failed} Dateien konnten nicht geladen werden. Der Download kann fortgesetzt werden.</small>`:""}</div>`}',
    ),
    (
        'const show=!navigator.onLine||readOfflinePrepState().running||readOfflinePrepState().status==="done";',
        'const st=readOfflinePrepState();const show=!navigator.onLine||st.running||st.status==="done"||st.status==="partial"||st.status==="error";',
    ),
    (
        'if(wrap.firstElementChild)box.appendChild(wrap.firstElementChild);',
        'if(wrap.firstElementChild)box.appendChild(wrap.firstElementChild);const resumeBtn=box.querySelector("#offlineResumeBtn");if(resumeBtn)resumeBtn.onclick=()=>startOfflinePreparation(true);',
    ),
    (
        'async function startOfflinePreparation(){\n  if(!("serviceWorker" in navigator)){alert("Service Worker ist auf diesem Gerät nicht verfügbar.");return}\n  if(readOfflinePrepState().running)return;\n  writeOfflinePrepState({running:true,status:"running",failed:0,loaded:0,total:0,percent:0,updatedAt:new Date().toISOString()});\n  updateOfflineBox();\n  const hint=$("offlinePrepHint");if(hint)hint.textContent="Offline-Paket wird vorbereitet ...";\n  const storage=await estimateOfflineStorage();\n  if(storage.estimate&&storage.estimate.quota&&storage.estimate.usage){\n    const free=Math.max(0,Number(storage.estimate.quota)-Number(storage.estimate.usage));\n    if(free<220*1024*1024){if(hint)hint.textContent=`Wenig freier Speicher: ${storageBytesLabel(free)} verfügbar. Vorbereitung läuft trotzdem.`}\n  }\n  const urls=await buildOfflinePrepareUrls();\n  await offlineDbSet("meta","syncStatus",{state:"running",count:urls.length,at:new Date().toISOString()});\n  const reg=await navigator.serviceWorker.ready;\n  reg.active?.postMessage({type:"OFFLINE_PREPARE",urls,requestedBy:"user"});\n}',
        'async function startOfflinePreparation(forceResume){if(!("serviceWorker" in navigator)){alert("Service Worker ist auf diesem Gerät nicht verfügbar.");return}repairOfflinePrepState();const state=readOfflinePrepState();if(state.running&&!offlinePrepIsStale())return;const resume=forceResume===true||offlinePrepShouldResume();writeOfflinePrepState({running:true,status:"running",failed:resume?state.failed||0:0,loaded:resume?state.loaded||0:0,total:resume?state.total||0:0,percent:resume?state.percent||0:0,updatedAt:new Date().toISOString()});updateOfflineBox();const hint=$("offlinePrepHint");if(hint)hint.textContent=resume?"Offline-Download wird fortgesetzt ...":"Offline-Paket wird vorbereitet ...";const storage=await estimateOfflineStorage();if(storage.estimate&&storage.estimate.quota&&storage.estimate.usage){const free=Math.max(0,Number(storage.estimate.quota)-Number(storage.estimate.usage));if(free<220*1024*1024){if(hint)hint.textContent=`Wenig freier Speicher: ${storageBytesLabel(free)} verfügbar. Vorbereitung läuft trotzdem.`}}const urls=resume?[]:await buildOfflinePrepareUrls();await offlineDbSet("meta","syncStatus",{state:"running",count:urls.length,at:new Date().toISOString()});const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:resume?"OFFLINE_PREPARE_RESUME":"OFFLINE_PREPARE",urls,requestedBy:resume?"resume":"user",resume});}',
    ),
    (
        '  if(data.type==="OFFLINE_PREPARE_DONE"){\n    const ok=!!data.ok;\n    writeOfflinePrepState({running:false,status:ok?"done":"error",total:Number(data.total||0),loaded:Number(data.loaded||0),failed:Number(data.failed||0),bytes:Number(data.bytes||0),percent:ok?100:Number(data.percent||0),updatedAt:new Date().toISOString()});\n    setJson(OFFLINE_SYNC_META_KEY,{appVersion:typeof APP_BUILD_ID==="string"?APP_BUILD_ID:"",contentVersion:String(window.__darRemoteBuildId||""),databaseSchemaVersion:OFFLINE_DB_VERSION,lastSuccessfulSync:ok?new Date().toISOString():(getJson(OFFLINE_SYNC_META_KEY,{lastSuccessfulSync:""}).lastSuccessfulSync||""),syncStatus:ok?"done":"error",pendingLocalChanges:getJson("darOfflineQueueCountV1",0),acknowledgedUpdateVersion:String(window.__darRemoteBuildId||"")});\n    offlineDbSet("meta","syncStatus",{state:ok?"done":"error",payload:data,at:new Date().toISOString()});\n    const hint=$("offlinePrepHint");\n    if(hint)hint.textContent=ok?"Offline-Nutzung vollständig eingerichtet":"Offline-Paket unvollständig. Bitte erneut starten.";\n    updateOfflineBox();\n    return;\n  }',
        '  if(data.type==="OFFLINE_PREPARE_STATUS"){if(data.running){writeOfflinePrepState({running:true,status:"running",updatedAt:new Date().toISOString()})}else if(data.progress){writeOfflinePrepState({running:false,status:"partial",total:Number(data.progress.total||0),loaded:Number(data.progress.loaded||0),failed:Number(data.progress.failed||0),bytes:Number(data.progress.bytes||0),percent:Number(data.progress.percent||0),updatedAt:data.progress.updatedAt||new Date().toISOString()})}else if(data.meta&&data.meta.ok){writeOfflinePrepState({running:false,status:data.meta.partial?"partial":"done",total:Number(data.meta.total||0),loaded:Number(data.meta.loaded||0),failed:Number(data.meta.failed||0),bytes:Number(data.meta.bytes||0),percent:100,updatedAt:data.meta.completedAt||new Date().toISOString()})}updateOfflineBox();return}\n  if(data.type==="OFFLINE_PREPARE_DONE"){const ok=!!data.ok;const partial=!!data.partial;const finalStatus=ok?(partial?"partial":"done"):"partial";writeOfflinePrepState({running:false,status:finalStatus,total:Number(data.total||0),loaded:Number(data.loaded||0),failed:Number(data.failed||0),bytes:Number(data.bytes||0),percent:ok?100:Number(data.percent||readOfflinePrepState().percent||0),updatedAt:new Date().toISOString()});setJson(OFFLINE_SYNC_META_KEY,{appVersion:typeof APP_BUILD_ID==="string"?APP_BUILD_ID:"",contentVersion:String(window.__darRemoteBuildId||""),databaseSchemaVersion:OFFLINE_DB_VERSION,lastSuccessfulSync:ok?new Date().toISOString():(getJson(OFFLINE_SYNC_META_KEY,{lastSuccessfulSync:""}).lastSuccessfulSync||""),syncStatus:ok?(partial?"partial":"done"):"partial",pendingLocalChanges:getJson("darOfflineQueueCountV1",0),acknowledgedUpdateVersion:String(window.__darRemoteBuildId||"")});offlineDbSet("meta","syncStatus",{state:finalStatus,payload:data,at:new Date().toISOString()});const hint=$("offlinePrepHint");if(hint)hint.textContent=partial?`Offline-Paket fast fertig (${data.failed||0} Dateien fehlgeschlagen). Download kann fortgesetzt werden.`:ok?"Offline-Nutzung vollständig eingerichtet":"Offline-Download kann fortgesetzt werden.";updateOfflineBox();return}',
    ),
    (
        'async function initOfflineEngine(){\n  readOfflinePrepState();\n  await offlineDbSet("meta","versions",{appVersion:typeof APP_BUILD_ID==="string"?APP_BUILD_ID:"",databaseSchemaVersion:OFFLINE_DB_VERSION,updatedAt:new Date().toISOString()});\n  if("serviceWorker" in navigator&&!window.__darOfflineMessageBound){\n    window.__darOfflineMessageBound=true;\n    navigator.serviceWorker.addEventListener("message",(ev)=>handleOfflineWorkerMessage(ev.data||{}));\n    try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:"OFFLINE_PREPARE_STATUS"})}catch(e){}\n  }\n  if(navigator.onLine)flushOfflineQueue().catch(()=>{});\n}',
        'async function initOfflineEngine(){readOfflinePrepState();repairOfflinePrepState();await offlineDbSet("meta","versions",{appVersion:typeof APP_BUILD_ID==="string"?APP_BUILD_ID:"",databaseSchemaVersion:OFFLINE_DB_VERSION,updatedAt:new Date().toISOString()});if("serviceWorker" in navigator&&!window.__darOfflineMessageBound){window.__darOfflineMessageBound=true;navigator.serviceWorker.addEventListener("message",(ev)=>handleOfflineWorkerMessage(ev.data||{}));try{const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:"OFFLINE_PREPARE_STATUS"})}catch(e){}}if(navigator.onLine){flushOfflineQueue().catch(()=>{});if(offlinePrepShouldResume()&&!window.__darOfflineAutoResumeStarted){window.__darOfflineAutoResumeStarted=true;setTimeout(()=>startOfflinePreparation(true).catch(()=>{}),1800)}}updateOfflineBox();}',
    ),
]

for path in FILES:
    text = path.read_text(encoding="utf-8")
    if CSS_ADD not in text:
        text = text.replace(
            ".offline-prep-progress span,.offline-prep-progress small{font-size:12px;color:var(--muted)}",
            ".offline-prep-progress span,.offline-prep-progress small{font-size:12px;color:var(--muted)}\n" + CSS_ADD,
            1,
        )
    for old, new in REPLACEMENTS:
        if old not in text:
            raise SystemExit(f"Missing pattern in {path}: {old[:80]}...")
        text = text.replace(old, new, 1)
    path.write_text(text, encoding="utf-8")
    print("Patched", path)
